### ISSUE TITLE
Use ObjectMapper 1.3.0

### ISSUE THREAD

**Issue by zellb** [tristanhimmelman/AlamofireObjectMapper#100]
Currently when I install AlamofireObjectMapper by pod install it installs ObjectMapper 1.2.0 to my project. I want to use ObjectMapper 1.3.0. Is that possible?

**Comment by tristanhimmelman** [comment]
Hmm that's odd. When I run `pod install` it has been installing ObjectMapper 1.3.0. 

The podspec has the following line: `s.dependency 'ObjectMapper', '~> 1.0'`

Which should install any version of ObjectMapper until 2.0. 

Perhaps try `pod update`?
