### ISSUE TITLE
AlamofireObjectMapper integration issue with Xcode 7.2.1 using cocoapod

### ISSUE THREAD

**Issue by ranjitDhiman1990** [tristanhimmelman/AlamofireObjectMapper#102]
I am integrating AlamofireObjetMapper in my project using cocoapods with Xcode 7.2.1 After pod file is being installed, whenever I'm opening the .xcworkspace and trying to build it shows me the errors attached in the image.

Please help me which version of AlamofireObjetMapper should I use with Xcode 7.2.1. 
<img width="1407" alt="screen shot 2016-05-20 at 12 41 24 am" src="https://cloud.githubusercontent.com/assets/15705575/15407097/edffd538-1e26-11e6-8e0e-0cafcae9cc15.png">

**Comment by tristanhimmelman** [comment]
You should be able to use any version of AlamofireObjectMapper. You will however, need to specify that it uses ObjectMapper v1.1.5 or earlier. If you include:
`pod 'ObjectMapper', '1.1.5'`
I believe that will fix your problem.

**Comment by ranjitDhiman1990** [comment]
Thanks for reply.
