### ISSUE TITLE
Tool to generate swift class

### ISSUE THREAD

**Issue by zh-wowtv** [tristanhimmelman/AlamofireObjectMapper#103]
Is there any tool to convert json file into swift class? Like:

http://www.jsonschema2pojo.org

**Comment by AFcgi** [comment]
Yes, look here:
https://github.com/insanoid/SwiftyJSONAccelerator

**Comment by lubecjac** [comment]
I have made a pull request to add this functionality, no idea if it'll be considered though. I didn't see a `CONTRIBUTING` file so I'm not sure if it fits the project or is formatted properly, but I at least gave it a shot. See #111.

**Comment by tristanhimmelman** [comment]
Closing this as it has been discussed several times in the ObjectMapper project.

I have decided not to include this functionality within the project to keep things as simple as possible. I am happy to link to tools that generate models in the README file though.
