### ISSUE TITLE
Cannot pass arguments in GET

### ISSUE THREAD

**Issue by JoeShi** [tristanhimmelman/AlamofireObjectMapper#107]
I am trying to append query parameters like normal Alamofire request. However. it shows me the following error message.

Error Messsage: 
```
'(dictionaryLiteral: (String, AnyObject))' is not convertible to '(dictionaryLiteral: (String, NSString)...)'
```

```
 Alamofire.request(.GET, NSURL(string: "movies/search", relativeToURL: XDMesssageAPIURL)!,
            parameters: ["title": self.title], encoding: .JSON, headers: nil)
        .validate()
        .responseObject { (response) in
            
        }
```

**Comment by tristanhimmelman** [comment]
I believe this is an Alamofire error. This extension does not do any processing of handling of GET parameters.

From the error message, it seems to me that the self.title is of the wrong type. You probably need to cast it to a String.
