### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by amolgupta** [tristanhimmelman/AlamofireObjectMapper#116]
Is there a way to use this with Swift 3 yet? Alamofire itself has a branch for Swift 3.0 which works well but this plugin shows compilation errors.

**Comment by TofPlay** [comment]
Same question as @amolgupta

**Comment by andre-wolfe** [comment]
Is swift 3.0 actually finalised at this point? I know the syntax is, but the API set into macOS/iOS seems to be in flux for the post WWDC pre-release time.

**Comment by tristanhimmelman** [comment]
There may still be changes... 

I have just created a fresh branch called `swift-3`. Feel free to create any PRs to upgrade the project to swift-3.0. I don't currently have time to do the migration.

**Comment by tristanhimmelman** [comment]
Hi all, I just updated the swift-3 branch. Everything is now up and running in the latest xcode 8 beta

**Comment by Gerst20051** [comment]
I'm getting a ton of ObjectMapper errors about inout.

<img width="540" alt="screenshot 2016-07-28 22 38 17" src="https://cloud.githubusercontent.com/assets/235372/17236055/0cde6220-5514-11e6-9147-877dda8fc3ec.png">

**Comment by Gerst20051** [comment]
Had to manually add ObjectMapper to my Podfile.

```pod 'ObjectMapper', :git => 'https://github.com/Hearst-DD/ObjectMapper.git', :branch => 'swift-3'```

**Comment by Stjng** [comment]
Can u guys solve this error? I'm using Xcode 8 beta 4 and my Podfile.
`pod 'AlamofireObjectMapper', :git => 'https://github.com/tristanhimmelman/AlamofireObjectMapper', :branch => 'swift-3'
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift3'
pod 'ObjectMapper', :git => 'https://github.com/Hearst-DD/ObjectMapper', :branch => 'swift-3'`
Thanks
<img width="845" alt="screenshot 2016-08-03 23 19 10" src="https://cloud.githubusercontent.com/assets/6636037/17373057/b95d5af4-59d0-11e6-856b-259717b2c3b6.png">
<img width="248" alt="screenshot 2016-08-03 23 18 58" src="https://cloud.githubusercontent.com/assets/6636037/17373058/b9b35eb8-59d0-11e6-8db9-66605ebe7035.png">

**Comment by amolgupta** [comment]
@Stjng this should be fixed now.
