### ISSUE TITLE
Not work in Xcod 7.0 beta

### ISSUE THREAD

**Issue by bagusflyer** [tristanhimmelman/AlamofireObjectMapper#12]
Got the following error message:

> The following build commands failed:
	CompileSwift normal x86_64 /Users/Public/Test/Projects/TestProject/Carthage/Checkouts/AlamofireObjectMapper/AlamofireObjectMapper/AlmofireObjectMapper.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

Any idea? Thanks

**Comment by pizthewiz** [comment]
Duplicate of #9, AlamofireObjectMapper does not yet support Swift 2.0.

**Comment by tristanhimmelman** [comment]
I have just created a branch with swift 2.0 support. See https://github.com/tristanhimmelman/AlamofireObjectMapper/tree/swift-2.0
