### ISSUE TITLE
Convert String to Int when mapping 

### ISSUE THREAD

**Issue by kamalupasena** [tristanhimmelman/AlamofireObjectMapper#122]
how can i convert string to int when mapping done ?
my json looks like this 
`{"programmes":[{"ID":"1","channelId":"1"}]}`
i need to get ID as a Int or NSNumber how can i archive this ?

**Comment by tristanhimmelman** [comment]
Please see the ObjectMapper project for this. You can use Transforms to convert your values while mapping. There should be an example of this in the Tests classes or in the github issues
