### ISSUE TITLE
How do map the json data if user enter incorrect detail?

### ISSUE THREAD

**Issue by dineshsharmav2** [tristanhimmelman/AlamofireObjectMapper#123]
My concern is that my request implementation with mapping object is working fine when user enter correct credential, but issue come when user enter incorrect details:

My Request to map the objects: 

**Alamofire.request(.POST, urlString, parameters: params, encoding: .JSON, headers: headers).responseObject(keyPath: "data") { (response: Response) in {

}**

Below is the JSON response when user entered incorrect credentials: { "success": "false", "message": "The User name or Password is incorrect.", "data": null }

Error when user enter incorrect details: Error : result : FAILURE: Error Domain=com.alamofire.error Code=-6004 "ObjectMapper failed to serialize response." UserInfo={NSLocalizedFailureReason=ObjectMapper failed to serialize response.}

**Please guide and suggest according this implementation.**

**Comment by waqqas-imena** [comment]
A similar question has already been asked before. Please read [this ](https://github.com/tristanhimmelman/AlamofireObjectMapper/issues/82)thread. 

You can create a `FailableObject<T:Mappable, E:Mappable>` where `T` is the expected type of the response, and `E` is the expected type of the Error.

**Comment by dineshsharmav2** [comment]
Hi waqqas-imena,
This done from my side but this was not easy as I thought. 
Thanks 
Dinesh S
