### ISSUE TITLE
associative collection parsing

### ISSUE THREAD

**Issue by antons81** [tristanhimmelman/AlamofireObjectMapper#124]
Hi I have JSON like this 

{
    "response": {
        "groups": {
            "123456": {
                "id": 1,
                "name": "group 1",
                "type": "group"
            },
            "67890": {
              "id": 2,
                "name": "group 2",
                "type": "group"
            }

        }
    }
 }

How I can parse it with alamofire properly? Please help

**Comment by tristanhimmelman** [comment]
Create a Group class that conforms to Mappable. Then you can map the groups as follows:

```
class Response: Mappable {
    var groups: [String: Group]?
    // init code

    func mapping(map: Map){
        groups <- map["groups"]
    }
}
```

**Comment by antons81** [comment]
And what method to send all to mapping from alamofire? In your examples its not so clear and old alamofire methods

**Comment by tristanhimmelman** [comment]
From my samples:
```
Alamofire.request(.GET, URL).responseObject { (response: Response<Response, NSError>) in
   
}
```

**Comment by antons81** [comment]
responseObject doesn't exist in Alamofire

**Comment by tristanhimmelman** [comment]
ResponseObject is the function that this extension provides...

You have to import AlamofireObjectMapper at the beginning of your file to have access to the functionality this extension provides.
