### ISSUE TITLE
Xcode 8 Beta 6 compatibility

### ISSUE THREAD

**Issue by Tulleb** [tristanhimmelman/AlamofireObjectMapper#128]
`swift-3` branch needs an update for the Xcode8b6 compatibility.

I tried to start a PR but there is some tricky issues...

**Comment by Tulleb** [comment]
Linked to #129.

**Comment by tristanhimmelman** [comment]
I just merged #129. Closing this

**Comment by Tulleb** [comment]
Hello @tristanhimmelman.

I am sorry but this #129 isn't fixing anything. This submission wasn't finished for sure.

I think you should reverse #129's commits and merge #130 instead.
