### ISSUE TITLE
AlmofireObjectMapper.swift Misspelled

### ISSUE THREAD

**Issue by alexanderjrobinson** [tristanhimmelman/AlamofireObjectMapper#13]
AlmofireObjectMapper should be renamed to AlamofireObjectMapper

**Comment by tristanhimmelman** [comment]
Thanks for pointing this out. I have fixed the issue

**Comment by wanbok** [comment]
It should be updated to CocoaPods.
Still misspelled, If user downloads this via CocoaPods

**Comment by tristanhimmelman** [comment]
I just push a new Podspec, so the latest changes should be updated on CocoaPods now.

**Comment by wanbok** [comment]
@tristanhimmelman :+1:
