### ISSUE TITLE
Pods giving compile time error

### ISSUE THREAD

**Issue by umairnow** [tristanhimmelman/AlamofireObjectMapper#14]
getting compile time error on this line mentioned below

<AppPath/AppName>/Pods/AlamofireObjectMapper/AlamofireObjectMapper/AlamofireObjectMapper.swift:49:10: Cannot invoke 'response' with an argument list of type '(queue: dispatch_queue_t?, serializer: GenericResponseSerializer<AnyObject>, (_, _, _, _) -> Void)'

<AppPath/AppName>/Pods/AlamofireObjectMapper/AlamofireObjectMapper/AlamofireObjectMapper.swift:98:10: Cannot invoke 'response' with an argument list of type '(queue: dispatch_queue_t?, serializer: GenericResponseSerializer<AnyObject>, (_, _, _, _) -> Void)'

**Comment by Pro2005** [comment]
I have the same error after update Alamofire (

**Comment by LouisDhauwe** [comment]
The parameter "serializer" has been renamed to "responseSerializer" in Alamofire 1.3.0.
I've made a pull request to fix this.

**Comment by umairnow** [comment]
When will they approve it? I need to decide immediately, whether should I go with this library or choose something else :)

**Comment by LouisDhauwe** [comment]
Hard to say, a workaround is to add the ObjectMapper dependency of this pod manually:
pod 'ObjectMapper', '~> 0.12'

and import 'AlamofireObjectMapper.swift' in your project (with the parameter fix).

**Comment by tristanhimmelman** [comment]
I've merged the pull request, but I am not able to push the Pod at this time. I am getting an error with the Alamofire (~> 1.3) dependency. I will try again a bit later on. 

Everything is now fine if you are using Carthage though.

You can always do as @LouisDhauwe suggested if you stuck.

**Comment by tristanhimmelman** [comment]
I was able to push the new Pod after this fix: http://stackoverflow.com/questions/18224627/error-on-pod-install

You should be good to go now using: 
pod 'AlamofireObjectMapper', '~> 0.6'

**Comment by umairnow** [comment]
Thanks for quick response, it is working now :+1:
