### ISSUE TITLE
(Swift 3) Xcode 8 GM not finding the Alamofire framework

### ISSUE THREAD

**Issue by timgcarlson** [tristanhimmelman/AlamofireObjectMapper#140]
I've had my project running the Swift 3 branch of AlamofireObjectMapper and Alamofire for the last week. Today I updated Xcode 8 from beta 6 to GM, and now AlamofireObjectMapper can't find any of the Alamofire classes. I'm getting the following errors in the AlamofireObjectMapper.swift file:

> Use of undeclared type 'Response'
> Use of undeclared type 'ResponseSerializer'

I've tried removing the pods and reinstalling them. I've also tried using commits of Alamofire from a couple days ago, since I know those were working this afternoon in Xcode 8 beta 6.

I'm also still getting this if I go back to beta 6. So not really sure what's going on.

Is this an isolated issue? Any ideas of what else I could try? Anyone else have issues when they went from beta to GM?

**Comment by limlab** [comment]
Have the same or related issue when moved from XCode 7.3.1 to 8 GM (I use Carthage)
```
*** Fetching AlamofireObjectMapper
*** Fetching ObjectMapper
*** Fetching Alamofire
*** Checking out Alamofire at "3.5.0"
*** Checking out AlamofireObjectMapper at "3.0.2"
*** Checking out ObjectMapper at "1.5.0"
*** xcodebuild output can be found in /var/folders/tn/v74xqr4s0qd3hly9fb8f72400000gn/T/carthage-xcodebuild.PK17XM.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "ObjectMapper-iOS" in ObjectMapper.xcworkspace
*** Building scheme "AlamofireObjectMapper iOS" in AlamofireObjectMapper.xcworkspace
** CLEAN FAILED **


The following build commands failed:
	Check dependencies
	Check dependencies
(2 failures)
** BUILD FAILED **


The following build commands failed:
	Check dependencies
	Check dependencies
(2 failures)
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/<USER>/Documents/Work/Swift/<APP_DIR>/Carthage/Checkouts/AlamofireObjectMapper/AlamofireObjectMapper.xcworkspace -scheme AlamofireObjectMapper iOS -configuration DEBUG -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **


The following build commands failed:
	Check dependencies
	Check dependencies
(2 failures)
** BUILD FAILED **


The following build commands failed:
	Check dependencies
	Check dependencies
(2 failures)

```

**Comment by tristanhimmelman** [comment]
I just merged a PR that should resolve these issues on the swift-3 branch. Please let me know if otherwise

**Comment by timgcarlson** [comment]
@tristanhimmelman That seems to have fixed it for me, thanks for the quick response!

**Comment by limlab** [comment]
Fixed issue for me too. Thanks!
