### ISSUE TITLE
Swift-3.0 is not available

### ISSUE THREAD

**Issue by ixialuo** [tristanhimmelman/AlamofireObjectMapper#144]
I use Swift-3.0 in xcode8 is not available

**Comment by swami701** [comment]
Could you guys please let us know when Swift-3.0 support will be available?

Thank you very much.

**Comment by qgliu** [comment]
ObjectMapper is swift-3.0 compatible, and Xcode 8 is breaking the code. Please upgrade and let us know the schedule. Thanks!

**Comment by sdtaheri** [comment]
Please fix this. Two of my projects which need updating rely on AlamofireObjectMapper.

**Comment by tristanhimmelman** [comment]
The Swift 3 branch has been merged into master and released.
