### ISSUE TITLE
Alamofire 4.0.0

### ISSUE THREAD

**Issue by ZKMax01** [tristanhimmelman/AlamofireObjectMapper#150]
Hey, got a question how to install AlamofireObjectMapper with new version of Alamofire 4.0.0.

After pod install
Terminal print:
- `Alamofire (~> 4.0)` required by `Podfile`
- `Alamofire (~> 3.2)` required by `AlamofireObjectMapper (3.0.2)`

**Comment by djardon** [comment]
Yo need to set the swift-3 branch, but still not work because have errors with ObjectMapper swift 3:

    pod 'Alamofire', '~> 4.0’
    pod 'AlamofireObjectMapper', :git => 'https://github.com/tristanhimmelman/AlamofireObjectMapper', :branch => 'swift-3'

**Comment by tristanhimmelman** [comment]
I have just released master with the Swift-3 changes, please use the latests

**Comment by Tulleb** [comment]
@tristanhimmelman error while `pod install`:

My podfile line:
`pod 'AlamofireObjectMapper'`

> - `Alamofire` required by `Podfile`
> - `Alamofire (= 4.0.0)` required by `Podfile.lock`
> - `Alamofire (~> 1.2)` required by `AlamofireObjectMapper (0.1)`

**Comment by tristanhimmelman** [comment]
@Tulleb I think you will need to run `pod update` to get the latest from AlamofireObjectMapper

**Comment by Tulleb** [comment]
Yes indeed @tristanhimmelman. Sorry for this mistake.

Thanks a lot for your reactivity!

**Comment by amolgupta** [comment]
could you also please update the Readme file. Lots of changes from the original. 
Thanks!
