### ISSUE TITLE
Response is now an undeclared type in Swift3 updates

### ISSUE THREAD

**Issue by qgliu** [tristanhimmelman/AlamofireObjectMapper#154]
Using the latest release with the swift 3 support, the following code show an error of "Use of undeclared type Response". Any migration breaking changes we should follow?
.responseObject { (response: Response<User, NSError>) in

**Comment by tristanhimmelman** [comment]
Yes, Alamofire updated the response object. Please use the following:
`.responseObject { (response: DataResponse<WeatherResponse>)`
