### ISSUE TITLE
swift-3 min deployment ios9?why ios8

### ISSUE THREAD

**Issue by AsTryE** [tristanhimmelman/AlamofireObjectMapper#157]
[!] Unable to satisfy the following requirements:

- `AlamofireObjectMapper (from `https://github.com/tristanhimmelman/AlamofireObjectMapper.git`, branch `bdbergeron-swift-3`)` required by `Podfile`

Specs satisfying the `AlamofireObjectMapper (from `https://github.com/tristanhimmelman/AlamofireObjectMapper.git`, branch `bdbergeron-swift-3`)` dependency were found, but they required a higher minimum deployment target.

**Comment by tristanhimmelman** [comment]
Hey there,
The reason I had to increase the min deployment target is because Alamofire has updated it to iOS 9. See we are dependant on Alamofire, we do not have a choice. https://github.com/Alamofire/Alamofire/blob/master/Alamofire.podspec

**Comment by AsTryE** [comment]
@tristanhimmelman thks,I know.

**Comment by chili-ios** [comment]
Hi there,
Alamofire now supports ios8. Could you please downgrade ios version in .podspec?

**Comment by tristanhimmelman** [comment]
@chili-ios I just released a new version with support for iOS 8
