### ISSUE TITLE
ObjectMapper failed to serialize response

### ISSUE THREAD

**Issue by asrivastav973** [tristanhimmelman/AlamofireObjectMapper#158]
Whenever the response contains any null value, it gives an error,

"FAILURE: Error Domain=com.alamofireobjectmapper.error Code=2 "ObjectMapper failed to serialize response." UserInfo={NSLocalizedFailureReason=ObjectMapper failed to serialize response.}"

This is how I am requesting

```
let URL = "https://demo6336282.mockable.io/myapi"
        Alamofire.request(URL).validate().responseObject { (response: DataResponse<WeatherResponse>) in

            let weatherResponse = response.result.value
            print(weatherResponse?.location)

            if let threeDayForecast = weatherResponse?.threeDayForecast {
                for forecast in threeDayForecast {
                    print(forecast.day)
                    print(forecast.temperature)           
                }
            }
        }
```
And this is my DataModel Class

```
import Foundation
import ObjectMapper
import AlamofireObjectMapper

class WeatherResponse: Mappable {
    var location: String? = ""
    var threeDayForecast: [Forecast]? = []

    required init?(map: Map){

    }

    func mapping(map: Map) {
        location <- map["location"]
        threeDayForecast <- map["three_day_forecast"]
    }
}

class Forecast: Mappable {
    var day: String? = ""
    var temperature: Int? = 0
    var conditions: String? = ""

    required init?(map: Map){

    }

    func mapping(map: Map) {
        day <- map["day"]
        temperature <- map["temperature"]
        conditions <- map["conditions"]
    }
}
```
I also tried adding blank parameters as this api requires no parameters and also added default URl encoding but no help.

I don't know where I am missing something, this code works fine when there is not any null in the api response. Please help!!

Thanks

**Comment by tristanhimmelman** [comment]
Are you still having this issue? Can you post the JSON response that is causing problems?

**Comment by asrivastav973** [comment]
The issue was resolved on the very next day, it was due to the malformed json. I was assuming that when no value is provided then it is null which was not the case. The mapper worked fine when null was present was in the response.

**Comment by zemadara** [comment]
the problem persist, do you have resolved it?
