### ISSUE TITLE
responseArray Cocoa 3840 error

### ISSUE THREAD

**Issue by igorpan** [tristanhimmelman/AlamofireObjectMapper#16]
I'm completely new to Swift/iOS development in general so pardon me if I've missed something obvious.
I have an API endpoint returning valid JSON Array:

```
[
    {
        "id":23,
        "amount":4000.0,
        "date":"2015-08-05",
        "description":null,
        "include_gst":true,
        "user_id":15,
        "gst_amount":363.6363636363636,
        "customer_id":null,
        "customer":null
    },
    {
        "id":19,
        "amount":150.0,
        "date":"2015-07-18",
        "description":"Proba",
        "include_gst":true,
        "user_id":15,
        "gst_amount":13.63636363636364,
        "customer_id":null,
        "customer":null
    }
]
```

However, when using `responseArray` method, it fails with the following error:

    error	NSError?	domain: "NSCocoaErrorDomain" - code: 3840	0x00007fc0abcd0230

Here is the code that produces it:

```
class RoundedClient {
    
    private var username: String?
    private var password: String?
    
    private let rootUrl = "http://localhost:3000/"

    func getIncomeRecords() -> Future<[IncomeRecord], RequestError> {
        let promise = Promise<[IncomeRecord], RequestError>()
        
        Alamofire.request(.GET, getUrl("income_records"))
            .authenticate(user: username!, password: password!)
            .responseArray { (response: [IncomeRecord]?, error: NSError?) in
                if response != nil {
                    promise.success(response!)
                } else {
                    promise.failure(RequestError(message: "Request failure"))
                }
            }
        
        return promise.future
    }
    
    private func getUrl(path: String) -> String {
        return rootUrl + path
    }

    class IncomeRecord: Mappable {
        var amount: Float?
        var description: String?
        var includeGst: Bool?
        
        static func newInstance() -> Mappable {
            return IncomeRecord()
        }
        
        func mapping(map: Map) {
            amount <- map["amount"]
            description <- map["description"]
            includeGst <- map["include_gst"]
        }
    }
}
```

Responses which return objects work fine with `responseObject` method. Could anybody shed some light on this?

**Comment by tristanhimmelman** [comment]
I tested your JSON response / models with ObjectMapper, and everything worked fine. 

The error the you posted has to do with JSON serialization. It could potentially have to do with the encoding http://stackoverflow.com/a/21076596/988336

The code you have above looks good to me.

Hope this helps

**Comment by igorpan** [comment]
Hey @tristanhimmelman yeah, I've searched quite a bit on Google but no avail. That answer mentions response charset not being utf-8, but my response headers seems to be ok:

![screen shot 2015-07-28 at 7 40 50 pm](https://cloud.githubusercontent.com/assets/2479869/8938739/b926229a-3560-11e5-8523-d009a04c18db.png)

**Comment by igorpan** [comment]
Ok, my mistake: my API endpoint returns HTML/JSON response depending on Accept header in the request. I haven't set it on my request so it was actually returning HTML data.

On related note, error does seem to be completely generic. I had to go through debugger to figure out the  actual error saying something like: "Invalid syntax error: unexpected character <". If that error would have bubbled up with that message up to the lib user, it would be a lot more easier to debug. So maybe I should open an issue on Alamofire?

**Comment by tristanhimmelman** [comment]
Glad you figured out the bug. 

Not a bad idea to file an issue with Alamofire.
