### ISSUE TITLE
 Unable to satisfy dependency requirements:

### ISSUE THREAD

**Issue by yerassyl** [tristanhimmelman/AlamofireObjectMapper#160]
Hello, here is the pod file I use:
  pod 'Alamofire', '~> 4.0'
  pod 'AlamofireObjectMapper', '~> 3.0'

when run "pod install" I get error:

[!] Unable to satisfy the following requirements:
- `Alamofire (~> 4.0)` required by `Podfile`
- `Alamofire (= 4.0.0)` required by `Podfile.lock`
- `Alamofire (~> 3.2)` required by `AlamofireObjectMapper (3.0.0)` 

If I comment out AlomofireObjectMapper everything is fine. Alamofire itself is being setup.

Does AOM work with Alamofire 4?

**Comment by csersurya** [comment]
I am also facing the same issue. Please help.

**Comment by tristanhimmelman** [comment]
Hi there, if you are using xcode 8 with swift 3, please use AlamofireObjectMapper 4.0.0. I just updated the ReadMe!
