### ISSUE TITLE
Cartfile in the 3.0.2 tag specifies incompatible dependency

### ISSUE THREAD

**Issue by kalkwarf** [tristanhimmelman/AlamofireObjectMapper#162]
I believe the 3.0.2 tag is intended to support Swift 2.3, but one of the dependencies specified in the Cartfile is not Swift 2.3 compatible.

Instead of
<code>
github "Alamofire/Alamofire" ~> 3.0.0
</code>

I think it should be
<code>
github "Alamofire/Alamofire" ~> 3.5
</code>

**Comment by kalkwarf** [comment]
Well, now I'm confused.

The Cartfile says
<code>github "Alamofire/Alamofire" ~> 3.0.0</code>
which gets resolved to
<code>github "Alamofire/Alamofire" "3.4.0"</code>
If I set the Cartfile to
<code>github "Alamofire/Alamofire" ~> "3.5"</code>
it resolves to
<code>github "Alamofire/Alamofire" "3.5.1"</code>

I'm not sure why

**Comment by tristanhimmelman** [comment]
Sorry for the confusion. I did not handle the migration to swift 2.3 then to swift 3.0 as well as I would have liked.

Moving forward I am only actively supporting swift 3
