### ISSUE TITLE
Extra Argument in call error

### ISSUE THREAD

**Issue by patchthecode** [tristanhimmelman/AlamofireObjectMapper#166]
Using your example, I get the following error message:

<img width="1009" alt="screen shot 2016-10-19 at 2 10 04 pm" src="https://cloud.githubusercontent.com/assets/2439146/19537680/c165e9f2-9605-11e6-9c1b-932f4e6addeb.png">

Using Alamofire 

```
pod 'Alamofire', '~> 4.0.1'
pod 'AlamofireImage', '~> 3.1'
pod 'AlamofireObjectMapper', '~> 4.0'
```

Is there something I am doing wrong?

**Comment by sakkeerhussain** [comment]
me too getting same issue, any solution for this.

**Comment by patchthecode** [comment]
@sakkeerhussain yea i found a solution.

basically, AlamoFire updated their code and therefore AlamoFire.request is no longer called like this.
he needs to update his documentation.
Alamofire code now looks something like this

```swift
Alamofire.request(link).responseObject { (response: DataResponse<T>) in
```

**Comment by sakkeerhussain** [comment]
Thanks @patchthecode
