### ISSUE TITLE
Can't append data response to class array

### ISSUE THREAD

**Issue by Jeffhabs** [tristanhimmelman/AlamofireObjectMapper#167]
Hello,

I am really struggling to get my response data into an array of my class. 

http://stackoverflow.com/questions/40168476/alamofireobjectmapper-cannot-save-data-response-in-object-array

Is there something I am doing wrong?

**Comment by tristanhimmelman** [comment]
From my quick look at you code, you MovieResults and MovieInfo class look fine.

This part of you code has one issue.
```
   Alamofire.request(URL).responseObject { ( response: DataResponse<MovieResults>) in

        let result = response.result.value

        if let movies = result?.movieResults {
            for item in movies {
                self.movieArray.append(item) //this doesn't work
                print(item.movieTitle) //this works
            }
        }
    }

    /* This doesn't print anything
        for some reason my array isn't truly being 
        popluated in the above fetchAPI call
    */
    for item in movieArray {
        print(item.movieTitle)
    }
```
The for loop at the end, is being called outside of the Alamofire response block. The Alamofire.request method is asynchronous, so you cannot expect the code within the block to be executed for the for loop that you placed right after. This for loop should be placed within the alamofire response block.

```
   Alamofire.request(URL).responseObject { ( response: DataResponse<MovieResults>) in

        let result = response.result.value

        if let movies = result?.movieResults {
            for item in movies {
                self.movieArray.append(item) //this doesn't work
                print(item.movieTitle) //this works
            }
        }

        for item in movieArray {
            print(item.movieTitle)
        }
    }


```
Hope this helps

**Comment by Jeffhabs** [comment]
Hey thanks for your response. That totally makes sense now, I didn’t realize that it was asynchronous.
In that case, I need a completion handler correct? Doesn’t DataResponse handle some of that?
