### ISSUE TITLE
AlamofireObjectMapper need compatible with ObjectMapper 2.2.0

### ISSUE THREAD

**Issue by liamscofield** [tristanhimmelman/AlamofireObjectMapper#170]
- `ObjectMapper (= 2.1.0)` required by `Podfile.lock`
- `ObjectMapper (~> 2.0)` required by `AlamofireObjectMapper (4.0.0)`
- `ObjectMapper (= 2.2.0)` required by `Moya-ObjectMapper/Core (2.0.1)`

**Comment by tristanhimmelman** [comment]
ObjectMapper (~> 2.0) required by AlamofireObjectMapper (4.0.0)

If you run a pod update, cocoapods should fetch the latest version of ObjectMapper (v2.2.1). Cocoapods is locked on `2.1.0` as you can see from your `Podfile.lock` file. `pod update` should resolve that

**Comment by txaiwieser** [comment]
Having this issue again, can we have another release to fix the version incompatibility? Thanks! 👍

**Comment by Swamiji** [comment]
I am also having the same issue with all suggested combinations for ObjectMapper and AlamofireObjectMapper.  Appreciate your help here. #

**Comment by litoarias** [comment]
I am having same error:

> My Cartfile
![captura de pantalla 2016-12-24 a las 16 46 36](https://cloud.githubusercontent.com/assets/7962872/21467767/8fe91580-c9f8-11e6-8818-1eaab59c5c5e.png)

> Term debug it's fine
![captura de pantalla 2016-12-24 a las 16 44 04](https://cloud.githubusercontent.com/assets/7962872/21467733/49058216-c9f8-11e6-8744-1f0abf338455.png)

> Same error when launch test app
![captura de pantalla 2016-12-24 a las 16 42 45](https://cloud.githubusercontent.com/assets/7962872/21467739/5afcc39e-c9f8-11e6-9479-eccaa8a34a13.png)

Could you help me thank you
