### ISSUE TITLE
Swift 2.3 alamofire 3.5.1 compatibility

### ISSUE THREAD

**Issue by demonar** [tristanhimmelman/AlamofireObjectMapper#178]
Is it possible to get a version compatible with alamofire 3.5.1 built in swift 2.3?

**Comment by demonar** [comment]
I forked the repo and created a branch, no code changes, only target updates.

https://github.com/demonar/AlamofireObjectMapper/tree/swift2.3alamofire3.5.1

**Comment by RomanVolkov** [comment]
If you're using cocoapods you can create pod install post build event that updates targets like this
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = "3.0"
          end
      end
but, instead of version 3.0 you can set 2.3

**Comment by demonar** [comment]
I'm using Carthage, that's why I created the fork and proposed the change

**Comment by RonnieRen** [comment]
we'd better have another release for swift 2.3 support by updating cartfile.resolve file to use correct version of Alamofire. also, use lagacy swift language version.

**Comment by demonar** [comment]
Yes,on the fork you'll see those changes
