### ISSUE TITLE
Is it support ios 7

### ISSUE THREAD

**Issue by SoonKong** [tristanhimmelman/AlamofireObjectMapper#18]
Is it support ios 7 ? 
Why did the message '[!] The platform of the target XXXX (iOS 7.0) may not be compatible with `AlamofireObjectMapper (0.2)` which has a minimum requirement of iOS 8.0 - OS X 10.9.' occur ？

**Comment by tristanhimmelman** [comment]
iOS 7 is not supported. You can still use this extension in iOS 7 by including the AlamofireObjectMapper.swift file directly in your project.
