### ISSUE TITLE
Crash on OM 2.2.2

### ISSUE THREAD

**Issue by haritowa** [tristanhimmelman/AlamofireObjectMapper#180]
[OM 2.2.2](https://github.com/Hearst-DD/ObjectMapper/releases/tag/2.2.2) includes [this](https://github.com/Hearst-DD/ObjectMapper/commit/f84c3f714e57762e27792b6ce6f5fb00c817214e) commit, which assert if anyone try to invoke non-throwing version of `map` for `ImmutableMappable` casted to `BaseMappable`. It's really good idea, but `AlamofireObjectMapper` is not ready for such change. Generic [method](https://github.com/tristanhimmelman/AlamofireObjectMapper/blob/master/AlamofireObjectMapper/AlamofireObjectMapper.swift#L95) create generic `ObjectMapperSerializer` under the hood, which type constrained to `BaseMappable`. Later, during serializing method, serializer [invokes](https://github.com/tristanhimmelman/AlamofireObjectMapper/blob/master/AlamofireObjectMapper/AlamofireObjectMapper.swift#L74) `map` without `try`, which leads to crash.

**Comment by haritowa** [comment]
I create a fix, but one question can't let me create a pr, what should i do with `mapToObject` for `ImmutableMappable`. My current fix allow to use instance, that conforming to `ImmutableMappable` protocol, and, if it implements `mapping` it will work, but `mapping` for `ImmutableMappable` seems lame and force developer to switch from `let` to `var`. Maybe `mapping` role should be reviewed for `ImmutableMappable`?

**Comment by tristanhimmelman** [comment]
@haritowa I have released a new update that has proper support for `ImmutableMappable`. I think your problems should be resolved now. THanks
