### ISSUE TITLE
JSON Array Response of Ints

### ISSUE THREAD

**Issue by alexduong** [tristanhimmelman/AlamofireObjectMapper#183]
What's the proper way to parse a JSON response with an array of ints?

The following doesn't work and throws a compiler.
Alamofire.request(url).responseArray { (response : DataResponse<[Int]>) in
 // Do something with response
}

I get this error.
Cannot convert value of type '(DataResponse<[Int]>) -> ()' to expected argument type '(DataResponse<[T]>) -> Void'

**Comment by tristanhimmelman** [comment]
Couple things to note:
1. When using `responseArray`, the type that you pass in as a generic should not be surrounded by the array brackets `[]`
2. `Int` does not conform to `Mappable`, therefore this type of call to `responseArray` will not work. The generic type you pass in must be a class/struct that conforms to Mappable. If you want to get an array of Ints, I would suggest you simply use the Alamofire `responseJSON` function.
