### ISSUE TITLE
Nested objects are always coming nil.

### ISSUE THREAD

**Issue by santhoshs5** [tristanhimmelman/AlamofireObjectMapper#184]
class UserInfo:Mappable
{
	var name:String?
	var identifier:String?
	var accountType:String?
	var devices:[UserDevice]?
	required init?(map: Map) {

    }
	
	 // Mappable
    func mapping(map: Map) {
        name    <- map["username"]
        identifier         <- map["identifier"]
        accountType       <- map["accountType"]
        devices  <- map["devices"]
    }
	
}

class UserDevice:Mappable
{
	var deviceName:String?
	var deviceType:String?
	var deviceIdentifier:String?
	
	required init?(map: Map) {

    }
	
	 // Mappable
    func mapping(map: Map) {
        deviceName    <- map["name"]
        deviceType         <- map["type"]
        deviceIdentifier       <- map["identifier"]
    }
	
}

Alamofire.request(request).responseObject{response<UserInfo> in 

let user = response.result.value 
}

This is my code my userdevices is coming nil always

**Comment by JGagnon91** [comment]
+1 i'm having the same issue.

I am receiving an Array of Guest objects, and each guest can have an array of Location objects. No matter what I try, my Location array is always nil.

**Comment by tristanhimmelman** [comment]
This looks like it should work to me. Please include a JSON sample so that we can help you better. I will close this ticket for now until you reply.
