### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by eman6576** [tristanhimmelman/AlamofireObjectMapper#185]
Will an update be made for Swift 3 support?

**Comment by pip8786** [comment]
I'm using it in a Swift 3 project and it seems to be fine. Seems like if you have 4.0.0 or later it should be good: https://github.com/tristanhimmelman/AlamofireObjectMapper/releases/tag/4.0.0

**Comment by tristanhimmelman** [comment]
@pip8786 is correct.
