### ISSUE TITLE
How can i print JSON 

### ISSUE THREAD

**Issue by santhoshs5** [tristanhimmelman/AlamofireObjectMapper#186]
I am using following method to parse the response.
        Alamofire.request(self.router).responseObject{ (response: DataResponse<Data>) in

I am getting data which custom model object.

**Comment by haraldmartin** [comment]
You can chain response handlers like this:
```swift
Alamofire.request(self.router)
  .responseJSON { (response) in
    print("json")
    print(response.result.value ?? "no json")
  }
  .responseObject { (response: DataResponse) in
    …
  }
```

See more https://github.com/Alamofire/Alamofire#chained-response-handlers

**Comment by yangjehpark** [comment]
And also, if you are handling the 'Mappable' model object, you can print like this.

```
func logJSON(mappable: Mappable) {
    print("\(mappable.toJSON())")
}
```
toJSON() is a 'Mappable' object's extension function.
