### ISSUE TITLE
AlamofireObjectMapper 4.x - SIGBART Exception

### ISSUE THREAD

**Issue by ozgur** [tristanhimmelman/AlamofireObjectMapper#189]
Here is my model:

```swift
import ObjectMapper

class IPAddress: Mappable {
  
  var address: String?
  
  required init?(map: Map) {
  }
  
  func mapping(map: Map) {
    address <- map["origin"]
  }
}
```

And when I do the following request, I get SIGBART in [line 74](https://github.com/tristanhimmelman/AlamofireObjectMapper/blob/b03ecca284d413225e0435d870da345d64458cc0/AlamofireObjectMapper/AlamofireObjectMapper.swift#L74):

```swift
Alamofire.request("http://httpbin.org/ip", method: .get)
  .responseJSON(completionHandler: { data in
    print("Data", data)
  })
  .responseObject(completionHandler: { (response: DataResponse<IPAddress>) in
    print("Response:", response)
  })
```

`.responseJSON` correctly prints the response data as dictionary.

Just did the following and it works fine:

```swift
Mapper<IPAddress>(context: nil).map(JSONObject: ["origin": "192.168.1.1"])
```

Tested with 4.0.0 and 4.0.1 via carthage.
I am using Swift 3.0 and Xcode 8.2.1. (Tested with iPhone 5s 10.2.1)

Tested on simulator and got the following error:

```swift
dyld: lazy symbol binding failed: Symbol not found: __TFC12ObjectMapper6MapperCfT7contextGSqPS_10MapContext___GS0_x_
  Referenced from: /Users/ozgur/Library/Developer/CoreSimulator/Devices/EB73481B-51CD-4138-B4E2-CC8014F7F7F1/data/Containers/Bundle/Application/5B26A070-18FA-4768-8391-F9BD8C59A1EB/TestApp.app/Frameworks/AlamofireObjectMapper.framework/AlamofireObjectMapper
  Expected in: /Users/ozgur/Library/Developer/CoreSimulator/Devices/EB73481B-51CD-4138-B4E2-CC8014F7F7F1/data/Containers/Bundle/Application/5B26A070-18FA-4768-8391-F9BD8C59A1EB/TestApp.app/Frameworks/ObjectMapper.framework/ObjectMapper

dyld: Symbol not found: __TFC12ObjectMapper6MapperCfT7contextGSqPS_10MapContext___GS0_x_
  Referenced from: /Users/ozgur/Library/Developer/CoreSimulator/Devices/EB73481B-51CD-4138-B4E2-CC8014F7F7F1/data/Containers/Bundle/Application/5B26A070-18FA-4768-8391-F9BD8C59A1EB/TestApp.app/Frameworks/AlamofireObjectMapper.framework/AlamofireObjectMapper
  Expected in: /Users/ozgur/Library/Developer/CoreSimulator/Devices/EB73481B-51CD-4138-B4E2-CC8014F7F7F1/data/Containers/Bundle/Application/5B26A070-18FA-4768-8391-F9BD8C59A1EB/TestApp.app/Frameworks/ObjectMapper.framework/ObjectMapper
```
Here is the similar SO question suffering from the very same issue:

http://stackoverflow.com/questions/41507502/alamofireobjectmapper-swift-line-74-works-in-playground-but-not-on-device-or-emu

**Comment by ozgur** [comment]
Found out the problem was about https://github.com/Hearst-DD/ObjectMapper/issues/722

Keeping it open so others might find it useful. @tristanhimmelman you can close it anytime you want.

Cheers.

**Comment by tristanhimmelman** [comment]
I've just release an update which resolves the issue. Please let me know if the problem persists.

https://github.com/tristanhimmelman/AlamofireObjectMapper/releases/tag/4.0.2
