### ISSUE TITLE
Struct nested can't be mapper

### ISSUE THREAD

**Issue by Shannon-Yang** [tristanhimmelman/AlamofireObjectMapper#190]
in `AlamofireObjectMapperTests's`  `testResponseObjectMapToObject()` method, If `WeatherResponse`  and it's nested objects `Forecast` are struct，will get  an error , `Forecast`'s array objects is nil, like this:

![609bd10b-0c6e-4597-888d-5f36c76c84ca](https://cloud.githubusercontent.com/assets/9735368/22873560/c22ced3e-f1fb-11e6-9377-861b2445396c.png)

![c28795e2-aa0d-4205-a5d2-f5abc81f3227](https://cloud.githubusercontent.com/assets/9735368/22873581/ecc13b72-f1fb-11e6-8a68-597d8dfb56e5.png)

If  `WeatherResponse` and `Forecast` is `Class`, will not have this error occurred, Why can not mapper a nested struct?

**Comment by tristanhimmelman** [comment]
Hi there,
Structs do actually work with ObjectMapper and AlamofireObjectMapper. The situation that does not work is mapping to an existing struct as the above screenshot is demonstrating. If you comment out that test, all the others should succeed.

**Comment by JonnyLinja** [comment]
Is this still the case? I appear to be struggling with this very issue. And if so, are there any plans to enable nested structs to work?

Thanks!
