### ISSUE TITLE
ObjectMapper required version needs to be updated

### ISSUE THREAD

**Issue by garie** [tristanhimmelman/AlamofireObjectMapper#192]
I had ObjectMapper at 2.2.1 and AlamofireObjectMapper at 4.0.2 and got a crash on missing symbol `shouldIncludeNilValues`, which looks like it was added in OM 2.2.2. The current version marked in the Cartfile for this project is 2.0. I think it just needs to be updated to require 2.2.2.

**Comment by tristanhimmelman** [comment]
#193 merged! Thx
