### ISSUE TITLE
A strange error

### ISSUE THREAD

**Issue by zhumi108** [tristanhimmelman/AlamofireObjectMapper#196]
I am using the basic Alamofire function like this:
```
Alamofire.request(url).responseJSON { (response: DataResponse<HomeArticle>) in
            print(response.result)
        }
```
The 'HomeArticle' is a custom class like this:
```
class HomeArticle: Mappable {
    var author_name: NSString?
    var commentCounts: Int?
    
    required init?(map: Map){
        
    }
    
    func mapping(map: Map) {
        author_name <- map["author_name"]
        commentCounts <- map["commentCounts"]
    }
}
```
 but somehow I got this error message: 'Cannot convert value of type '(DataResponse\<HomeArticle\>) -> ()' to expected argument type  '(DataResponse\<Any\>) -> void''
It seems that 'HomeArticle -> Any' is wrong, or did I use it incorrectly?

**Comment by naturalwarren** [comment]
I'm experiencing the same thing - any updates here?

**Comment by naturalwarren** [comment]
I imported `AlamofireObjectMapper` and was able to write the following successfully:

```
 Alamofire.request(request.url(), headers: Api.HEADERS).responseObject { (response: DataResponse<PriceEstimateResponse>) in
```

**Comment by fukemy** [comment]
i imported AlarmofireObjectMapper but still got this error:

![screen shot 2018-07-24 at 15 40 52](https://user-images.githubusercontent.com/8202437/43126812-ffcec7d4-8f57-11e8-807c-87231764d24c.png)

plz help

**Comment by fukemy** [comment]
here is manager:
```
var manager: SessionManager {
        let manager = Alamofire.SessionManager.default
        manager.session.configuration.timeoutIntervalForRequest = 20
        
        return manager
    }
```

**Comment by fukemy** [comment]
then here is ResponseModel class:
```

import ObjectMapper

class ResponseModel : Mappable{
    
    var result : Any?
    var success : Any?
    var error : Any?
    
    required init?(map: Map){
        
    }
    
    func mapping(map: Map) {
        result <- map["location"]
        success <- map["success"]
        error <- map["error"]
    }
}
```
