### ISSUE TITLE
Framework wont compile

### ISSUE THREAD

**Issue by omarojo** [tristanhimmelman/AlamofireObjectMapper#198]
I cloned your project. But I cant compile the frameworks, because it doesnt have the dependencies for Alamofire and ObjectMapper included in the project.

![image](https://cloud.githubusercontent.com/assets/995265/23815664/f17e73d6-059d-11e7-93de-0cf1c6fae8fe.png)

**Comment by tristanhimmelman** [comment]
You will need to use carthage to load the dependencies.
