### ISSUE TITLE
Doesn't support on iOS 7 because import Alamofire and ObjectMappe

### ISSUE THREAD

**Issue by GuyKahlon** [tristanhimmelman/AlamofireObjectMapper#20]
The main problem is that iOS 7 doesn't support dynamic frameworks.

You can fix that with preprocessor flag ( Thanks to RxSwift :) ).

Add RX_NO_MODULE as a custom Swift preprocessor flag

#if !AOM_NO_MODULE
import Alamofire
import ObjectMappe
#endif

Thanks,
Guy

**Comment by AFcgi** [comment]
Hey @GuyKahlon 

there are some solutions, for example like this: https://medium.com/ios-os-x-development/how-to-use-swift-cocoapods-and-still-support-ios-7-0-f9dc29b3628b

**Comment by tristanhimmelman** [comment]
I don't not plan on supporting iOS 7. You should still be able to use this project for iOS 7 by including the AlamofireObjectMapper.swift file directly into your project.
