### ISSUE TITLE
ResponseArray not available in this version?

### ISSUE THREAD

**Issue by CedricVanhaverbeke** [tristanhimmelman/AlamofireObjectMapper#203]
Hi!

I should be able to get an array of objects in just 1 line using request.responseArray(). This method does not seem to exist? Any thoughts?

**Comment by tristanhimmelman** [comment]
Hey @CedricVanhaverbeke,

Not sure why you are experiencing difficulties as this method still exists:
```
public func responseArray<T: BaseMappable>(queue: DispatchQueue? = nil, keyPath: String? = nil, context: MapContext? = nil, completionHandler: @escaping (DataResponse<[T]>) -> Void) -> Self
```

**Comment by CedricVanhaverbeke** [comment]
Can you give an example with this method?

**Comment by tristanhimmelman** [comment]
Please see the tests included in this project
