### ISSUE TITLE
how to deal this json，this key i can't get value

### ISSUE THREAD

**Issue by IAskWind** [tristanhimmelman/AlamofireObjectMapper#205]
{
    "submiturl": "api/mobile/process/submit",
    "formkey": "",
    "pro_tender_reg.type": [
        {
            "zy": "1",
            "hz": "2"
        }
    ],
    "pro_tender_reg.cjbm_id": {
        "xxaqb": 50,
        "jtkhb": 52,
        "xtjcb": 51
    }
}

my deal:

class BbmsqxxModel: Mappable {
    var submiturl: String = ""
    var formkey : String = ""
    var pro_tender_reg_type = [Dictionary<String, String>()]
    var pro_tender_reg_cjbm_id = [Dictionary<String, Int>()]

    required init?(map: Map){
        
    }
    
    func mapping(map: Map) {
        submiturl <- map["submiturl"]
        formkey <- map["formkey"]
        pro_tender_reg_type <- map["pro_tender_reg.type"]
        pro_tender_reg_cjbm_id <- map["pro_tender_reg.cjbm_id"]
    }
    
}

but i don't get  'pro_tender_reg.type' value , please help me

**Comment by tristanhimmelman** [comment]
See https://github.com/Hearst-DD/ObjectMapper#easy-mapping-of-nested-objects

You will need to do something like:
`map["pro_tender_reg.type" nested: false]`

**Comment by IAskWind** [comment]
thanks your help, i get value about it.

        pro_tender_reg_type <- map["pro_tender_reg.type", nested: false]
        pro_tender_reg_cjbm_id <- map["pro_tender_reg.cjbm_id", nested: false]
