### ISSUE TITLE
Is it possible to map the first object in JSON Array?

### ISSUE THREAD

**Issue by dinaraja** [tristanhimmelman/AlamofireObjectMapper#219]
In `ObjectMapper`, It is possible to map the object with index of item in JSON Array like below.
`distance <- map["distances.0.value"]`

Is it possible to do the same with this one? It's not working when I tried to parse the object with `distances.0` to assign an object.

**Comment by tristanhimmelman** [comment]
Hi @dinaraja, that should indeed be working. There is an example of it working in the NestedArrayTests.swift file. Hope this helps
ex:
```
object <- map["objects.0"]
```
