### ISSUE TITLE
Swift 4 With ObjectMapper

### ISSUE THREAD

**Issue by joebenton** [tristanhimmelman/AlamofireObjectMapper#222]
I'm trying to use your Swift 4 branch with cocoa pods:

  pod 'AlamofireObjectMapper', :git => 'https://github.com/tristanhimmelman/AlamofireObjectMapper.git', :branch => 'swift-4'

However, the dependency of your library ObjectMapper needs to use the swift-4 branch too but not sure how to achieve that?

The issue I am having is that I am getting compile errors in Xcode 9 with Object Mapper with toIntMac() is unavailable.

Any ideas on how I can get the ObjectMapper pod to use the swift 4 branch along with the swift 4 branch of your library?

**Comment by antonyjamese** [comment]
I am too facing the same error. Does the pod is ready for swift4 without any error?

**Comment by wkq87** [comment]
@joebenton Hi ,I met the same problem. How did your solve this issue and can you tell me the resolution?
Thanks a lot

**Comment by joebenton** [comment]
If I remember, I just used the swift-4 branch, and then de-integrated and re-installed the pods and it seemed to be okay.
