### ISSUE TITLE
please support swift 4

### ISSUE THREAD

**Issue by Colin225** [tristanhimmelman/AlamofireObjectMapper#227]
please support swift 4, thanks!

**Comment by steelzeh** [comment]
This worked for me, use this until swift 4 branch is merged.
pod "AlamofireObjectMapper", :git => 'https://github.com/tristanhimmelman/AlamofireObjectMapper.git', :branch => 'swift-4'

**Comment by tristanhimmelman** [comment]
Just released the swift 4 version.

**Comment by robinkunde** [comment]
@tristanhimmelman When will this version be available through Cocoapods?

**Comment by steelzeh** [comment]
@robinkunde this worked for me. 
:git => 'https://github.com/tristanhimmelman/AlamofireObjectMapper'
and then pod update

**Comment by robinkunde** [comment]
@steelzeh I'm using it as a dependency in a Podspec, so this doesn't work for me, unfortunately.

**Comment by tristanhimmelman** [comment]
@robinkunde sorry, I forgot to push the pod when I released! It should now be good to go.

**Comment by robinkunde** [comment]
@tristanhimmelman Thank you!
