### ISSUE TITLE
How to map JSON objects inside JSON array without a name before the object ?

### ISSUE THREAD

**Issue by Mohammed-Eliass** [tristanhimmelman/AlamofireObjectMapper#230]
I got this response from some api :

        [
           {
              "status": true,
              "client_token": "eyJ0eXAjksdfhjdsfksdafjdsjlfjasjkdlkasdjklasjd"
          },
         {
             "headers": {},
             "original": {
                                 "status": true,
                                 "message": "We Recieved your all information."
                              },
             "exception": null
         }
]

How could I map JSON objects without name before the object inside the array.

**Comment by tristanhimmelman** [comment]
Please see the `responseArray` method instead of the `responseObject` method

**Comment by Mohammed-Eliass** [comment]
Thanks man I know  `responseArray ` with solve the array kind of JSON response, but my Question is " How to parse two different objects without names inside array ? "
