### ISSUE TITLE
Xcode9 and swift4 Errors

### ISSUE THREAD

**Issue by wkq87** [tristanhimmelman/AlamofireObjectMapper#233]
i update to Xcode9 and change the Podfile to 
`pod "AlamofireObjectMapper", :git => 'https://github.com/tristanhimmelman/AlamofireObjectMapper.git', :branch => 'swift-4'`
But when i run pod install, follow error coming:
`[!] Unable to satisfy the following requirements:

- `ObjectMapper (~> 3.0)` required by `AlamofireObjectMapper (5.0.0)`

None of your spec sources contain a spec satisfying the dependency: `ObjectMapper (~> 3.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.`

**Comment by joebenton** [comment]
Remove ObjectMapper from your pod file as the pod 'AlamofireObjectMapper' is already linking in ObjectMapper

**Comment by wkq87** [comment]
@joebenton thank you, i update the pod repo, and the issue  gone
