### ISSUE TITLE
String Changes

### ISSUE THREAD

**Issue by bracketslash** [tristanhimmelman/AlamofireObjectMapper#235]
'characters' is deprecated: Please use String or Substring directly
at HexColorTransform.swift line 38 and 92
and at ToJSON.swift line 37

'CharacterView' is deprecated: Please use String or Substring directly
at ToJSON.swift line 44

**Comment by tristanhimmelman** [comment]
This is a issue with ObjectMapper which has now been resolved in version 3.1.0
