### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by ayking** [tristanhimmelman/AlamofireObjectMapper#236]
Hi,
As Swift have slow app startup time issue due to loading frameworks and Swift Package Manager can solve it. so can you help to add SPM support ?

**Comment by ayking** [comment]
Close as it is no support iOS yet

**Comment by AFcgi** [comment]
There are ways to use the SPM for iOS. Please reopen the issue again.

**Comment by Drusy** [comment]
`Alamofire` and `ObjectMapper` use SPM already, would be nice ot have `AlamofireObjectMapper` too

**Comment by TomasHubelbauer** [comment]
An open issue requesting this: #120.
