### ISSUE TITLE
Generic Structs

### ISSUE THREAD

**Issue by aliiizzz** [tristanhimmelman/AlamofireObjectMapper#239]
hello, i have a Json like this:
`{
    "data": [
        {
            "id": 54,
            "title": "test",
            "cities": {
                "data": [
                    {
                        "id": 55,
                        "title": "test"
                    },
                    {
                        "id": 56,
                        "title": "test"
                    }
                    ] 
            }
        }
        ]
}`
and i am trying to map this with generics because i have many responses like this tha contain data object.
i have a struct like this:
```
 import ObjectMapper
 struct ServiceResponse<T> : Mappable {
    var response: [T]?
    init?(map: Map) {
    }
    mutating func mapping(map: Map) {
        response <- map["data"]
    }
 }
```
but it is always nil, if i use specific type instead of T it works like charm. any suggestions?

**Comment by mdathersajjad** [comment]
Same problem. My JSON is a generic response object {"succes":"true","errorMessage":"Message","data": "[]/{}" }. So i created a generic class as @aliiizzz . All other fields are mapping except data. It is always nil.

**Comment by gcharita** [comment]
Generic type `T` should implement `Mappable` protocol. 

So, simply use the following struct instead and it will work:

```swift
import ObjectMapper
struct ServiceResponse<T: Mappable> : Mappable {
    var response: [T]?
    init?(map: Map) { }
    mutating func mapping(map: Map) {
        response <- map["data"]
    }
}
```

**Comment by NrmeenTomoum** [comment]
```

 class Response<T> : Mappable
 {
    var Result : T?
    required init?(map: Map){

    }
    func mapping(map: Map) {
        Result <- map["Result"]
    }
    
}

  private func mainRequest<T>(httpMethod : HTTPMethod ,urlParameters : [String : AnyObject],URL : String,completionHandler: @escaping (Response<T>) -> Void)
    {
        Alamofire.request(URL, method: httpMethod , parameters: urlParameters, encoding: JSONEncoding.default, headers: nil).responseObject{(response: DataResponse<Response<T>>)  in
            let respons = response.result.value
            completionHandler(respons!)
            
        }
    }
```
 this is Generic Method I used  with. object Mapper   
   
     ```
           mainWorker.mainRequest(httpMethod:HTTPMethod.post, urlParameters: urlParameters , URL: URL)
                { (respond: Response<String>) in
                    print("========>", respond.Result )
        
                }
```
