### ISSUE TITLE
[Question] How can I concatenate two variables?

### ISSUE THREAD

**Issue by haroldogtf** [tristanhimmelman/AlamofireObjectMapper#245]
How can I concatenate two variables?

Example:
`url <- map ["path"] + map ["extension"]`

**Comment by tiwariammit** [comment]
first fetch two object on different variables and then add it.
You can do like this:-

var path : String?
var extension : String?
path <- map ["path"]
path <- map ["extension"]
url = path! + extension!

**Comment by haroldogtf** [comment]
Thank you!
