### ISSUE TITLE
I always got ObjectMapper failed to serialize response

### ISSUE THREAD

**Issue by Dr1992** [tristanhimmelman/AlamofireObjectMapper#246]
Hello dude, Please help me.

URL (GET) - "https://api.github.com/repos/ReactiveCocoa/ReactiveCocoa/pulls?state=all"

![image](https://user-images.githubusercontent.com/17261405/39675272-190c51d8-512f-11e8-9924-fd7084fd0d52.png)

This is what i get when i print the responseString
![image](https://user-images.githubusercontent.com/17261405/39675440-85adb870-5131-11e8-8907-32980aed7c08.png)

![image](https://user-images.githubusercontent.com/17261405/39675344-2bfda4f8-5130-11e8-93c9-049e7468e32d.png)
...

Mapper below

![image](https://user-images.githubusercontent.com/17261405/39675356-72c9d6ea-5130-11e8-8d0e-23b61d810128.png)

I always got   
![image](https://user-images.githubusercontent.com/17261405/39675368-b017e91a-5130-11e8-89e5-e9ee8cc6b1f4.png)

**Comment by tiwariammit** [comment]
Hello i have done in simple way. 



class DiegoramosalmeidaModel{
    
    class func getDiegoramosalmeida(){
        
        let url = "https://api.github.com/repos/ReactiveCocoa/ReactiveCocoa/pulls?state=all"

        Alamofire.request(url, method: .get).responseJSON { (response) in
            hideProgressHUD()
            let status = response.response?.statusCode
            print("STATUS \(status)")
            
            switch response.result{
            case .success(let value):
                print(value)
                
                if let val = value as? [[String : Any]]{
                    
                    let model = Mapper<PullRequest>().mapArray(JSONArray: val)
                    print(model)
                    
                }else{
                    
                    print("unable To Map")
                }
                
            case .failure(let error):
                print(error)
            }
        }
    }
}




class PullRequest: Mappable {
    
    var id:Int?
    var title: String?
    var description: String?
    var url:String?
    var root : Int?
    
    var htmlUrl : String?
    var diffUrl : String?
    var patchUrl : String?

    var user : User?
    
    
    required init?(map: Map) {
        
    }
    
    func mapping(map: Map) {
        
        id <- map["id"]
        title <- map["title"]
        description <- map["description"]
        
        htmlUrl <- map["html_url"]
        diffUrl <- map["diff_url"]
        patchUrl <- map["patch_url"]
        
        user <- map["user"]
    }
}

class User : Mappable{
    
    var id:Int?
    var login: String?
    var avatarUrl: String?
    var url:String?

    required init?(map: Map) {
        
    }
    
    func mapping(map: Map) {
        
        id <- map["id"]
        login <- map["login"]
        avatarUrl <- map["avatar_url"]
        url <- map["url"]

    }
}

**Comment by tiwariammit** [comment]
If any problem fill free to ask me.
