### ISSUE TITLE
Swift 4.2 and Xcode 10 compatibility

### ISSUE THREAD

**Issue by MindaugasJucius** [tristanhimmelman/AlamofireObjectMapper#249]
Any plans to update `ObjectMapper` dependency to 3.3.0 version? 
Currently this library doesn't compile on Swift 4.2

**Comment by kidsid-Ixigo** [comment]
Yes, please. Much needed. Just need to bump ObjectMapper version in podspec.

**Comment by tristanhimmelman** [comment]
I just released a new version with the updated dependency
