### ISSUE TITLE
Conversion to swift 4.2 is available

### ISSUE THREAD

**Issue by jeewancti** [tristanhimmelman/AlamofireObjectMapper#257]
Hi,
I am on version 5.0.1 but still getting this error "Conversion to swift 4.2 is available"

**Comment by mobinzk** [comment]
You can add this to the end of your Podfile

`post_install do |installer|
  myTargets = ['AlamofireObjectMapper']

  installer.pods_project.targets.each do |target|
    if myTargets.include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
  end
end`

**Comment by tristanhimmelman** [comment]
This should be resolved on v5.2.0 which i just released. Please let me know if not.
