### ISSUE TITLE
Swift 2.0 problems

### ISSUE THREAD

**Issue by Urkman** [tristanhimmelman/AlamofireObjectMapper#26]
I get a lot of problem when using your Swift 2.0 branch with Alamo Swift 2.0 and ObjectMapper Swift 2.0 branches...

**Comment by tristanhimmelman** [comment]
Can you please be more specific? 

The Swift 2.0 version of ObjectMapper has a significant change in it's protocol. This is likely the problem you are seeing. It should be simple enough to update your models to the new protocol.

**Comment by ynnckcmprnl** [comment]
I'm getting the following error when compiling:

`Module file's minimum deployment target is ios8.3 v8.3: /Users/Yannick/Development/Redacted/Carthage/Build/iOS/AlamofireObjectMapper.framework/Modules/AlamofireObjectMapper.swiftmodule/x86_64.swiftmodule`

Deployment target of my project was originally 8.0, setting it to 8.3 or 8.4 does not solve the issue.

**Comment by Urkman** [comment]
It was a problem with .reponseObhect()...
But I solved it now :)

Thanks for your work...
