### ISSUE TITLE
Upgrade dependencies to use latest beta of Alamofire beta-5

### ISSUE THREAD

**Issue by sumac13** [tristanhimmelman/AlamofireObjectMapper#267]
There was an important bug fix in beta-5 of alamofire which fixes a problem where App Store Connect would reject builds containing a `-` in the bundle version fields which meany any .ipa including Alamofire would be rejected by ASC see [here 2797](https://github.com/Alamofire/Alamofire/issues/2797). Any project which uses this library therefore can't be uploaded successfully to ASC without it being updated first to use this fixed version of Alamofire.

**Comment by RomanPodymov** [comment]
Hello @sumac13 
I hope that the problem is solved in [this pull request](https://github.com/tristanhimmelman/AlamofireObjectMapper/pull/271).
