### ISSUE TITLE
Error when building AlamofireObjectMapper (6.0.0) with Xcode 10.2 & Swift 5

### ISSUE THREAD

**Issue by YMonnier** [tristanhimmelman/AlamofireObjectMapper#270]
Pods
```
Analyzing dependencies
Downloading dependencies
Using Alamofire (5.0.0-beta.6)
Using AlamofireObjectMapper (6.0.0)
Using ObjectMapper (3.4.2)
```

<img width="415" alt="Screenshot 2019-04-27 at 7 12 31 PM" src="https://user-images.githubusercontent.com/9322425/56852872-cebeee00-6920-11e9-9379-9c5ebd67e28c.png">

**Comment by komandirdk** [comment]
Has anyone found a solution to this problem?

**Comment by nlhdung** [comment]
I have the same issue :(

**Comment by mat-kul** [comment]
> Pods
> 
> ```
> Analyzing dependencies
> Downloading dependencies
> Using Alamofire (5.0.0-beta.6)
> Using AlamofireObjectMapper (6.0.0)
> Using ObjectMapper (3.4.2)
> ```
> 
> <img alt="Screenshot 2019-04-27 at 7 12 31 PM" width="415" src="https://user-images.githubusercontent.com/9322425/56852872-cebeee00-6920-11e9-9379-9c5ebd67e28c.png">

The quickest solution is to provide default value, in this case just pass `.main` DispatchQueue, like below:

`return response(queue: queue ?? .main, responseSerializer: DataRequest.ObjectMapperSerializer(keyPath, mapToObject: object, context: context), completionHandler: completionHandler)`

**Comment by tiwariammit** [comment]
Have same issue did anyone solved it?

**Comment by tiwariammit** [comment]
Have same issue did anyone solved it?

<img width="741" alt="Screen Shot 2019-05-05 at 1 22 27 PM" src="https://user-images.githubusercontent.com/22368948/57190349-dee65700-6f38-11e9-9a26-64d20cf45ad3.png">

**Comment by YMonnier** [comment]
Nop! I changed the library of my project... Now I am using Moya + ObjectMapper

**Comment by RomanPodymov** [comment]
Fixed in [this pull request](https://github.com/tristanhimmelman/AlamofireObjectMapper/pull/271). As temporal solution you can add the following line to your Podfile:
`pod 'Alamofire', '5.0.0-beta.3'`

**Comment by KieranLafferty** [comment]
Still stuck on this 
<img width="272" alt="Screen Shot 2019-05-21 at 2 39 31 PM" src="https://user-images.githubusercontent.com/778142/58132501-4d344600-7bd6-11e9-94fe-6df1f9f991d4.png">

Was able to resolve other issues locally but it appears it can't differentiate between the method signatures in ImmutableMappable and Mappable's implementation of `.mapArray(JSONObject:)`

Currently blocked on moving to swift 5 on this 😭

**Comment by RomanPodymov** [comment]
Hello @KieranLafferty 
I cannot reproduce the issue you reported. Do you use **CocoaPods** to install **AlamofireObjectMapper**? If so do you have the following line `pod 'AlamofireObjectMapper', :git => 'https://github.com/RomanPodymov/AlamofireObjectMapper.git', :branch => 'master'` in your Podfile?

**Comment by davisford** [comment]
Is there a solution for Carthage users?

**Comment by RomanPodymov** [comment]
Hello @davisford 
Replace `github "tristanhimmelman/AlamofireObjectMapper" ~> 5.2` with `github "RomanPodymov/AlamofireObjectMapper" "master"` in your Cartfile.

**Comment by RomanPodymov** [comment]
Hello @YMonnier 
#271 was merged to master. Are you still able to reproduce the issue?

**Comment by YMonnier** [comment]
Seems good with `AlamofireObjectMapper 6.1.0` via Cocoapods ;)

**Comment by RomanPodymov** [comment]
> Seems good with `AlamofireObjectMapper 6.1.0` via Cocoapods ;)

In such case close the issue.
