### ISSUE TITLE
How to make post in AlamofireObjectMapper ?

### ISSUE THREAD

**Issue by mash3l777** [tristanhimmelman/AlamofireObjectMapper#273]

**Comment by tiwariammit** [comment]
Here is the code for making .post request:-

 let sessionsManager = AlamofireAppManager.session
 sessionsManager.startRequestsImmediately = true
let dataRequest: DataRequest = sessionsManager.request("your api url", method: .post, parameters: "parameter", encoding: "encoding if need", headers: "header")

dataRequest.responseObject { (response: DataResponse<T>) in 

print(response)
}


If there is any confusion then feel free to ask the question.

**Comment by mash3l777** [comment]
Yes Thank you Bro
I used like this :

```
Alamofire.request(URL , method: .post , parameters: parameters, encoding: JSONEncoding.default).responseObject { (response: DataResponse<LoginResultDto>)
                 in
```
