### ISSUE TITLE
Updating podspec to swift 5

### ISSUE THREAD

**Issue by tirrorex** [tristanhimmelman/AlamofireObjectMapper#276]
Hello,
Since the 6.0 and master are using Alamofire 5.0 beta (which uses swift 5 since beta 4), isn't it possible to do a quick release or update master to use the last version of Alamofire ?

Currently the lib still uses swift 4.2 which prevents us from updating our library to swift 5.

**Comment by RomanPodymov** [comment]
Hello @tirrorex 
Could you please check if the issue is reproducing with AlamofireObjectMapper 6.1.0?

**Comment by tirrorex** [comment]
Hello, @RomanPodymov i can tell you just by looking at the commits that it will not pass the lint process (some changes i made in my branch are missing).
The library compiling in a project and linting it as a dependency are two separated things.

**Comment by sal1980** [comment]
Hi @tirrorex, can you publish 5.2.1 version on Cocoapods for swift 5 support?

**Comment by RomanPodymov** [comment]
Hello @tirrorex 
What error do you get on `pod spec lint`?

**Comment by tristanhimmelman** [comment]
6.2.0 should resolve this issue
