### ISSUE TITLE
Is there any version compatible with alamofire 5.0.0-beta.3 ? 

### ISSUE THREAD

**Issue by Mohammed-Eliass** [tristanhimmelman/AlamofireObjectMapper#281]
I'm trying to use the `Alamofire 5.0.0-beta.3`, but when I try `AlamofireObjectMapper 5.2`
I got `Alamofire 4.8`

when I try `AlamofireObjectMapper 6.0`, I got `Alamofire 5.0.0-beta.6`

Any ideas ?

**Comment by RomanPodymov** [comment]
Hello @Mohammed-Eliass 
Why do you need to use Alamofire 5.0.0-beta.3?

**Comment by tristanhimmelman** [comment]
The latest release targets Alamofire 5.0.0-rc2
