### ISSUE TITLE
Can not able to install version 6.2.0 using cocopod 

### ISSUE THREAD

**Issue by samir76Git** [tristanhimmelman/AlamofireObjectMapper#307]
![Screenshot 2020-06-01 at 6 13 50 PM](https://user-images.githubusercontent.com/37202608/83410287-ba0e2d00-a433-11ea-9da8-3043e58d3a05.png)

**Comment by RomanPodymov** [comment]
Hello @samir76Git 
AlamofireObjectMapper 6.2.0 requires iOS 10.0. Please check the minimum deployment target in your project.

**Comment by samir76Git** [comment]
@RomanPodymov 
My project minimum deployment target is iOS 10.0.

**Comment by sijjeel** [comment]
Hi, I am getting this error...
[!] CocoaPods could not find compatible versions for pod "Alamofire":
  In snapshot (Podfile.lock):
    Alamofire (= 5.2.1, ~> 5.2)

  In Podfile:
    Alamofire (~> 5.2)

    AlamofireObjectMapper (~> 5.2) was resolved to 5.2.1, which depends on
      Alamofire (~> 4.7)

Although i am using same version 5.2 of both Alamofire and AlamofireObjectMapper.

**Comment by samir76Git** [comment]
in my profile.pod file deployment target less than iOS 10.
now it's working.

Thanks @RomanPodymov
