### ISSUE TITLE
Pod can`t install

### ISSUE THREAD

**Issue by ppamorim** [tristanhimmelman/AlamofireObjectMapper#32]
Hi.
The cocoapods returns:

    [!] Unable to satisfy the following requirements:
                                                                                                                              
    - `Alamofire (~> 2.0.2)` required by `Podfile`                                                                                
    - `Alamofire (= 2.0.2)` required by `Podfile.lock`                                                                            
    - `Alamofire (= 2.0.0)` required by `AlamofireObjectMapper (0.9)`

My Podfile:

    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '8.0'
    use_frameworks!

    target 'Doge' do
        pod 'PureLayout'
        pod 'RealmSwift'
        pod 'Alamofire', '~> 2.0.2'
        pod 'ObjectMapper', '~> 0.17'
        pod 'Nuke'
        pod 'kingpin'
    end

Anyone knows what can be?

**Comment by tristanhimmelman** [comment]
I've created a new release which should fix this. Please try version 1.0

**Comment by ppamorim** [comment]
Do you know what`s happens here? I already have imported the library...

![captura de tela 2015-09-24 as 22 00 16](https://cloud.githubusercontent.com/assets/5521682/10090593/b603bb5c-6307-11e5-8db5-cb90ecf50f3d.png)

**Comment by iosdevuz** [comment]
Hello i have like this error:

- `ObjectMapper` required by `Podfile`
- `ObjectMapper (= 2.2.2)` required by `Podfile.lock`
- `ObjectMapper (~> 2.0)` required by `AlamofireObjectMapper (4.0.1)`
- `ObjectMapper (~> 2.0.0)` required by `GoogleMapsDirections (1.1.0)`

This is my pod file:

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'BarakaCardiOS' do
  use_frameworks!

 pod 'SlideMenuControllerSwift'

 pod 'Alamofire'
 pod 'AlamofireObjectMapper'
 pod 'AlamofireImage', '~> 3.1'
 pod 'AlamofireNetworkActivityIndicator', '~> 2.0'

 pod 'SwiftyJSON'
 pod 'SnapKit', '~> 3.0.2'

 pod 'Localize-Swift', '~> 1.7'
 pod 'GoogleMapsDirections', '~> 1.1'
 pod 'ObjectMapper'
 pod 'GoogleMaps'
