### ISSUE TITLE
Alamofire 3.0 Support

### ISSUE THREAD

**Issue by mabril** [tristanhimmelman/AlamofireObjectMapper#34]
This is not working with lastest version of Alamofire 3.0

**Comment by patricks** [comment]
+1

**Comment by ivosabev** [comment]
+1

**Comment by evautherin** [comment]
+1

**Comment by RodolfoGS** [comment]
+1

**Comment by mabril** [comment]
For all of you, I solved it in my Pull request.

Try it!

https://github.com/tristanhimmelman/AlamofireObjectMapper/pull/36

**Comment by tristanhimmelman** [comment]
I have created a branch for Alamofire 3.0 support using @mabril pull request. Please work off this branch until Alamofire 3.0 is fully released

https://github.com/tristanhimmelman/AlamofireObjectMapper/tree/alamofire3.0
