### ISSUE TITLE
AlamofireObjectMapper does not support Alamofire 3.0

### ISSUE THREAD

**Issue by biguas** [tristanhimmelman/AlamofireObjectMapper#38]
I need Alamofire 3.0 to fix some issues and I got this error when also getting Alamofire 1.0.

Can someone add compatibility?

**Comment by pizthewiz** [comment]
Check out the [alamofire3.0](https://github.com/tristanhimmelman/AlamofireObjectMapper/tree/alamofire3.0) branch.

**Comment by jscg719** [comment]
how to use alamofire3.0 branch in Podfile?

**Comment by biguas** [comment]
Thanks!!
But i got this error now, just after try to build AlamofireObjectMapper:

CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 9.0'
A shell task failed with exit code 65:
2015-10-09 19:13:11.622 xcodebuild[17485:888896] [MT] PluginLoading: Required plug-in compatibility UUID 0420B86A-AA43-4792-9ED0-6FE0F2B16A13 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Lin.xcplugin' not present in DVTPlugInCompatibilityUUIDs

**Comment by pizthewiz** [comment]
> how to use alamofire3.0 branch in Podfile?
I don't use CocoaPods so you'll have to check the docs to see if/how to specify a branch.

> But i got this error now, just after try to build AlamofireObjectMapper:
Hmm, the logging seems to be complaining about a third-party Xcode plug-in. Anecdotally, I'm using the branch and able to build/run with Xcode 7.0.1 / 10.11.1.

**Comment by tristanhimmelman** [comment]
I also, do not use Cocoapods that much. However according to the docs you can use the following format:
```
pod 'AFNetworking', :git => 'https://github.com/gowalla/AFNetworking.git', :branch => 'dev'
```
See for more detail:
https://guides.cocoapods.org/syntax/podfile.html#pod

**Comment by tristanhimmelman** [comment]
Alamofire 3.0 support is now on master with a new release: 1.1.0

**Comment by srinivasanVaradan** [comment]
Alamofire.request(_,_).responseObject gives error in Alamofire3.0 ..
The error msg is :" Value of type 'Request' has no member responseObject "

**Comment by biguas** [comment]
Thanks @tristanhimmelman :+1: It's not getting any errors now.
