### ISSUE TITLE
tvOS + Pods

### ISSUE THREAD

**Issue by hessela** [tristanhimmelman/AlamofireObjectMapper#48]
When i try to add/install the objectmanager via cocoapods by adding:

pod 'AlamofireObjectMapper', '~> 2.0'

and run 'pods install'

With 'platform :tvos, '9.0'

It tells me that The platform of the target 'Pods' is not compatible with 'AlamoforeObjectManager (2.0.0)', which does not support 'tvos'.

Is cocoapods not supported yet on the new version, that been added 2 days ago, telling that tvos is now supported??

/Anders

**Comment by tristanhimmelman** [comment]
Hi there,

The latest version 2.0.2 should now be good to go with tvOS. Please let me know if otherwise.

Thanks
