### ISSUE TITLE
Code signing failure when building 2.0.1

### ISSUE THREAD

**Issue by pizthewiz** [tristanhimmelman/AlamofireObjectMapper#49]
Something seems awry yet with the code signing setup in the project file, when building from source:
```sh
…
*** Checking out AlamofireObjectMapper at "2.0.1"
…
*** Building scheme "AlamofireObjectMapper iOS" in AlamofireObjectMapper.xcworkspace
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 9.1'
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

Building 2.0.0 has no such issue.

**Comment by tristanhimmelman** [comment]
Sorry about that, I was messing around with the code signing when trying to fix some issues with TravisCI. I will push an update shortly. Thanks for the heads up

**Comment by pizthewiz** [comment]
No worries, sorry I couldn't provide a bit more detail aside from it not working but wanted to make sure to flag the issue. Definitely digging the new `Response` stuff!

**Comment by tristanhimmelman** [comment]
Nice, glad you like it! It cleans stuff it up :).

I just pushed 2.0.2. I think everything is sorted out. Please let me know if you still have a problem.

**Comment by pizthewiz** [comment]
Seems to be working now, thanks for the fix!
