### ISSUE TITLE
Handle Nested JSON properties

### ISSUE THREAD

**Issue by btelintelo** [tristanhimmelman/AlamofireObjectMapper#5]
lets say i get back json like this:

{
 locations{
 }
 forecasts{
}
types
{
}
}

When I call responseObject or responseArray, I want to do that for one specific property.  For example,
.responseArray { (response: <- [Location]?, "locations", error: NSError?) in

I don't care about forecasts or types in this instance.  Perhaps this is an easy way to do this now I am missing.

**Comment by tristanhimmelman** [comment]
There is no short cut for mapping just one of the sub types of a response. The easiest way to get what you mentioned about is probably the following:
```
class WeatherResponse: Mappable {
	var locations: [Location]?
	
	required init?(_ map: Map) {
		mapping(map)
	}
	func mapping(map: Map) {
		locations <- map["locations"]
	}
}
```

Then you could access the locations in 
```
.responseObject {(response: WeatherResponse?, error: NSError?) in {
      println(response?.locations)
}
```

ObjectMapper does allow you to map nested objects simply (https://github.com/Hearst-DD/ObjectMapper#easy-mapping-of-nested-objects) however, the top level response object needs to be present for AlamofireObjectMapper to work.

Hope this helps

**Comment by btelintelo** [comment]
Thanks, it helps!  I was trying to avoid adding a layer of boilerplate code and also not polluting the model.

**Comment by santhoshs5** [comment]
Alamofire.request(self.loginRouter).responseObject{ (response: DataResponse<UserInfo>) in
{
**response.result.value.devices is nil  WHY**
}

JSON : 

{
name:""
devices"{
a={
name = ""
value = ""
};
b = {
name = ""
value = ""
};
}

class UserInfo:Mappable
{
var name:String?
var device:[Device]?
    required init?(map: Map) {
        mapping(map: map)
    }

    func mapping(map: Map) {
        userDevices  <- map["devices"]
        name <- map["name"]
}

class device:Mappable{
var name:
required init?(map: Map) {
    }
    func mapping(map: Map) {
}
}

}


Let me know what i am doing wrong why my nested object devices is nil
