### ISSUE TITLE
Building for iphonesimulator

### ISSUE THREAD

**Issue by AAverin** [tristanhimmelman/AlamofireObjectMapper#55]
when installing via Carthage building for iphonesimulator fails if signature is not present (no iPhone developer account)
Base ObjectMapper library builds fine for iphonesimulator target

**Comment by AAverin** [comment]
This PR for Carthage actually says that having iPhone Developer account is no longer a requirement to build for iPhone Simulator and debugging
https://github.com/Carthage/Carthage/pull/583

**Comment by AAverin** [comment]
The bug is in the iOS target build settings - it requires signature for iOS Simulator, while the correct value should be 'Don't sign'. Changing it resolves the problem

**Comment by AAverin** [comment]
Looks like manual change in the project settings and building in Carthage results in Xcode crashes on breakpoints that are set inside closer of responseObject() method.
Any way this could be fixed in repository?

**Comment by AAverin** [comment]
Crash when breakpoint is inside responseObject()
https://gist.github.com/AAverin/e3d293ca168b53443773

**Comment by tristanhimmelman** [comment]
Hi @AAverin, 

I'm not sure exactly what is causing the problem you are experiencing... I just created a new project using Carthage and I was able to put a break point within the responseObject() function without a problem.

**Comment by AAverin** [comment]
The case might be that I don't have iOS developer license and build for simulator-only.

**Comment by tristanhimmelman** [comment]
I think you are probably right about this...
