### ISSUE TITLE
ResponseObject, ResponseArray does not work for nested path

### ISSUE THREAD

**Issue by avshiyanov** [tristanhimmelman/AlamofireObjectMapper#57]
For Example if I have response starts with metadata.results I get serialization error:
 Alamofire.request(.GET, BaseURL
        ,parameters: ["page": "0", "maxitems": "20"])
        .responseObject("metadata.results") { (response: Response<T, NSError>) in
                print (response)
        };

Error: FAILURE: Error Domain=com.alamofire.error Code=-6004 "ObjectMapper failed to serialize response." UserInfo={NSLocalizedFailureReason=ObjectMapper failed to serialize response.}

**Comment by tristanhimmelman** [comment]
These should work as I have tests in place to ensure that they do.

Please paste you JSON response and your models so that I can help you better

**Comment by tristanhimmelman** [comment]
My mistake, I just realized that I have not realized AlamofireObjectMapper since adding the nested key paths feature.

Please get the lasted release: 2.1.0

**Comment by mandeepsangwan21** [comment]
hi i'm try to implement the code from this link of yours
https://github.com/tristanhimmelman/AlamofireObjectMapper

but im getting error
"getEvents error: Error Domain=com.alamofire.error Code=-6004 \"ObjectMapper failed to serialize response.\" UserInfo={NSLocalizedFailureReason=ObjectMapper failed to serialize response.}"

**Comment by tristanhimmelman** [comment]
@mandeepsangwan21, my mistake, the example was using the wrong URL. I've updated it now. It should have been:
https://raw.githubusercontent.com/tristanhimmelman/AlamofireObjectMapper/2ee8f34d21e8febfdefb2b3a403f18a43818d70a/sample_keypath_json
