### ISSUE TITLE
ObjectMapper failed to serialize response

### ISSUE THREAD

**Issue by RafaelRViana** [tristanhimmelman/AlamofireObjectMapper#58]
Hi,

I'm trying to use AlamofireObjectMapper in a project with Switf 2 on Xcode 7. 

I mapped an object into a class:
import Foundation
import ObjectMapper

class Item: Mappable {
    var id: Int?
    required init?(_ map: Map) {
    }
    func mapping(map: Map) {
        id <- map["id"]
    }
}

However, when I call it (as Github's example)
let URL = "xxx"
Alamofire.request(.GET, URL)
            .responseObject("data") { (response: Response<Item, NSError>) in
                print(response.result.value?.id)
                print(response.result.error)
            }

I got this error:
"Optional(Error Domain=com.alamofire.error Code=-6004 "ObjectMapper failed to serialize response." UserInfo={NSLocalizedFailureReason=ObjectMapper failed to serialize response.})"

This also happens with WeatherForecast example. What can be the problem?

**Comment by loopingGIT** [comment]
i can't even compile, i get an error Value of type Request has no member 'responseObject'
Using swift 2.0 and xCode 7

**Comment by tristanhimmelman** [comment]
I'm not sure why this is happening for you two... have you included the following line in your file?
```import AlamofireObjectMapper```

**Comment by loopingGIT** [comment]
that did it. thanks.

**Comment by priya-vr** [comment]
i have the same issue "Value of type request has no member .responseObject",
import AlamofireObjectMapper is already added but issue is still exist.
