### ISSUE TITLE
array response with key

### ISSUE THREAD

**Issue by smoi** [tristanhimmelman/AlamofireObjectMapper#61]
my server returns a response like this

{data:[array of devices]}

How can i get those kind of data? If I do responseArray i can't get it. If i do responseObject("data") I can't use an array. How should I do? Is this possible with object mapper?

**Comment by tristanhimmelman** [comment]
You should be able to use this function:
```
public func responseArray<T: Mappable>(keyPath: String, completionHandler: Response<[T], NSError> -> Void) -> Self
```

**Comment by smoi** [comment]
Workend like a charm, thanks!

**Comment by jbehrens94** [comment]
How would I do this in the current version? That function doesn't exist anymore, afaik.
