### ISSUE TITLE
** BUILD FAILED **

### ISSUE THREAD

**Issue by paulomcnally** [tristanhimmelman/AlamofireObjectMapper#63]
*** Fetching AlamofireObjectMapper
    *** Fetching Alamofire
    *** Fetching ObjectMapper
    *** Checking out ObjectMapper at "1.0.1"
    *** Checking out Alamofire at "3.1.4"
    *** Checking out AlamofireObjectMapper at "2.1.0"
    *** xcodebuild output can be found in /var/folders/gp/5xhpyxj54pvb185s6t67sp980000gp/T/carthage-xcodebuild.TEJVi6.log
    *** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
    *** Building scheme "Alamofire OSX" in Alamofire.xcworkspace
    *** Building scheme "Alamofire tvOS" in Alamofire.xcworkspace
    *** Building scheme "Alamofire watchOS" in Alamofire.xcworkspace
    *** Building scheme "ObjectMapper-Mac" in ObjectMapper.xcworkspace
    *** Building scheme "ObjectMapper-watchOS" in ObjectMapper.xcworkspace
    *** Building scheme "ObjectMapper-tvOS" in ObjectMapper.xcworkspace
    *** Building scheme "ObjectMapper-iOS" in ObjectMapper.xcworkspace
    *** Building scheme "AlamofireObjectMapper iOS" in AlamofireObjectMapper.xcworkspace
    *** Building scheme "AlamofireObjectMapper watchOS" in AlamofireObjectMapper.xcworkspace
    ** BUILD FAILED **
    
    
    The following build commands failed:
    	CompileSwift normal armv7k /Users/paulomcnally/github/SelfieDescuentos/Carthage/Checkouts/AlamofireObjectMapper/AlamofireObjectMapper/AlamofireObjectMapper.swift
    	CompileSwiftSources normal armv7k com.apple.xcode.tools.swift.compiler
    (2 failures)
    /Users/paulomcnally/github/SelfieDescuentos/Carthage/Checkouts/AlamofireObjectMapper/AlamofireObjectMapper/AlamofireObjectMapper.swift:31:8: error: module file's minimum deployment target is watchos2.1 v2.1: /Users/paulomcnally/Library/Developer/Xcode/DerivedData/AlamofireObjectMapper-ekvtjzjwgicbrdffunyfsynwdcib/Build/Products/Release-watchos/ObjectMapper.framework/Modules/ObjectMapper.swiftmodule/arm.swiftmodule
    A shell task failed with exit code 65:
    ** BUILD FAILED **
    
    
    The following build commands failed:
    	CompileSwift normal armv7k /Users/paulomcnally/github/SelfieDescuentos/Carthage/Checkouts/AlamofireObjectMapper/AlamofireObjectMapper/AlamofireObjectMapper.swift
    	CompileSwiftSources normal armv7k com.apple.xcode.tools.swift.compiler
    (2 failures)

**Comment by dsato80** [comment]
+1

**Comment by tristanhimmelman** [comment]
This should be fixed in 2.1.1 which I just released
