### ISSUE TITLE
responseArray build error

### ISSUE THREAD

**Issue by anilustel** [tristanhimmelman/AlamofireObjectMapper#65]
I'm using request for "responseArray" but build failed with this error:

**Cannot invoke 'responseArray' with an argument list of type '((Response<[CouponResponse], NSError>) -> Void)'**

Code:
**Alamofire.request(.GET, URL).responseArray { (response: Response<[CouponResponse], NSError>) -> Void in
            if let couponRes = response.result.value {
                print(couponRes[0].result)
            }
        }**

How to solve this problem? Thx

**Comment by tristanhimmelman** [comment]
Did you `import AlamofireObjectMapper` at the beginning of your file?

**Comment by anilustel** [comment]
Yes,

**import Alamofire
import ObjectMapper
import AlamofireObjectMapper**

these all imported.

**Comment by tristanhimmelman** [comment]
Can you post `CouponResponse` please

**Comment by anilustel** [comment]
Ohh my God!
Sooo sorry! I forgot to put **:Mappable** for my class.

Thx, solved! :)

**Comment by tristanhimmelman** [comment]
hehe no problem :+1:
