### ISSUE TITLE
I always got 'objectmapper failed to serialize response' when parsing error response 

### ISSUE THREAD

**Issue by macbaszii** [tristanhimmelman/AlamofireObjectMapper#66]
```swift
import Foundation
import ObjectMapper
import AlamofireObjectMapper

private let NameKey = "name"
private let DescriptionKey = "description"
private let CoverURLKey = "cover_url"
private let MembersAmountKey = "members_count"
private let SportNameKey = "sport_name"
private let PagePolicyKey = "policy"

class Tribe: Mappable {
    var name: String?
    var desc: String?
    var coverURL: NSURL?
    var membersAmount: Int?
    var sportName: String?
    var policy: ObjectPolicy?
    required init?(_ map: Map){
        
    }
    
    func mapping(map: Map) {
        name <- map[NameKey]
        desc <- map[DescriptionKey]
        coverURL <- (map[CoverURLKey], URLTransform())
        membersAmount <- map[MembersAmountKey]
        sportName <- map[SportNameKey]
        policy <- map[PagePolicyKey]
    }
}
```

this is my class and I just used simply -responseObject object method in APIClient
Thank in advance.

**Comment by JayachandraA** [comment]
Hello dude!, The same thing happening to me as well. When I run your code for single object it is giving 
__Error Domain=com.alamofire.error Code=-6004 "ObjectMapper failed to serialize response." UserInfo={NSLocalizedFailureReason=ObjectMapper failed to serialize response.}__

let URL = "https://raw.githubusercontent.com/tristanhimmelman/AlamofireObjectMapper/d8bb95982be8a11a2308e779bb9a9707ebe42ede/sample_json"
Alamofire.request(.GET, URL).responseObject("data") { (response: Response<WeatherResponse, NSError>) in

    let weatherResponse = response.result.value
    print(weatherResponse?.location)

    if let threeDayForecast = weatherResponse?.threeDayForecast {
        for forecast in threeDayForecast {
            print(forecast.day)
            print(forecast.temperature)           
        }
    }
}


__So please help me out of from this.__

**Comment by macbaszii** [comment]
@JayachandraA bad news, I dogged into the code and this library have just written an extension with own serializer and fixed error message for us.

I think the proper way is clone this repository and edit the serializer yourself.

**Comment by tristanhimmelman** [comment]
ObjectMapper doesn't yet support specific error messaging when parsing errors occur. This is why this extension simply reports the same error.

@JayachandraA, looking at the sample you are trying to run, I can see the error by looking at the JSON response linked. You are trying to deserialize using `data` as a keypath but `data` isn't in the JSON response. Try again but omit the keypath.

**Comment by JayachandraA** [comment]
@tristanhimmelman  @macbaszii  thanks guys for your response. finally I found the solution.

**Comment by macbaszii** [comment]
@JayachandraA What was your solution ? Could you share to us ?

**Comment by JayachandraA** [comment]
@macbaszii I just assigned empty values when I'm declaring optional properties 
like this
    _var name: String? = ""
    var desc: String? = ""
    var coverURL: NSURL? = nil
    var membersAmount: Int? = 0
    var sportName: String? = ""_

**Comment by BerkinSi** [comment]
@tristanhimmelman Hello I am having the same issue. I'll really appreciate if one can help me immediately, i really need a quick response.
**Here is an example returning json** 
->
[
  {
    "eventdescription": "event2",
    "participantid": "{7,2,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL}",
    "mainphotoid": 3,
    "photosid": "{7,3,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL}",
    "ownerid": 2,
    "invitationlist": "{7,4,6,8,NULL,NULL,NULL,NULL,NULL,NULL}",
    "privilligeId": "{7,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL}",
    "eventid": 2,
    "eventdate": "2016-10-05 00:00:00",
    "eventitle": "Come on first2"
  },
  {
    "eventdescription": "asd",
    "participantid": "{9,1,2,3,NULL,NULL,NULL,NULL,NULL,NULL}",
    "mainphotoid": 2,
    "photosid": "{1,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL}",
    "ownerid": 2,
    "invitationlist": "{2,4,7,8,NULL,NULL,NULL,NULL,NULL,NULL}",
    "privilligeId": "{1,2,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL}",
    "eventid": 3,
    "eventdate": "2016-10-05 00:00:00",
    "eventitle": "asdas"
  },
  {
    "eventdescription": "UpdateasddddLet's starts",
    "participantid": "{9,1,2,3,NULL,NULL,NULL,NULL,NULL,NULL}",
    "mainphotoid": 2,
    "photosid": "{1,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL}",
    "ownerid": 3,
    "invitationlist": "{2,4,7,8,NULL,NULL,NULL,NULL,NULL,NULL}",
    "privilligeId": "{1,2,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL}",
    "eventid": 4,
    "eventdate": "2016-10-05 00:00:00",
    "eventitle": "asdasd"
  },
  null,
  null,
  null,
  null,
  null,
  null,
  null
]
**Here is my class to create mappable**
->
<img width="413" alt="screen shot 2016-06-15 at 03 52 21" src="https://cloud.githubusercontent.com/assets/14097119/16064740/9bb8bf5c-32ac-11e6-93db-3690638a4b81.png">

I have set the initial values to nil regarding @JayachandraA 's solution. before setting them to nil, i gave them values of "" (if they are string), 0(if they are int), [""] (string array), [0] (int array)

**This is my request** 
->

<img width="693" alt="screen shot 2016-06-15 at 03 56 02" src="https://cloud.githubusercontent.com/assets/14097119/16064815/1f31ecf0-32ad-11e6-8e00-39398c5c827a.png">

**This is what i get when i print the responseString**

Success: true
Response String: Optional("[{\"eventdescription\":\"event2\",\"participantid\":\"{7,2,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL}\",\"mainphotoid\":3,\"photosid\":\"{7,3,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL}\",\"ownerid\":2,\"invitationlist\":\"{7,4,6,8,NULL,NULL,NULL,NULL,NULL,NULL}\",\"privilligeId\":\"{7,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL}\",\"eventid\":2,\"eventdate\":\"2016-10-05 00:00:00\",\"eventitle\":\"Come on first2\"},{\"eventdescription\":\"asd\",\"participantid\":\"{9,1,2,3,NULL,NULL,NULL,NULL,NULL,NULL}\",\"mainphotoid\":2,\"photosid\":\"{1,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL}\",\"ownerid\":2,\"invitationlist\":\"{2,4,7,8,NULL,NULL,NULL,NULL,NULL,NULL}\",\"privilligeId\":\"{1,2,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL}\",\"eventid\":3,\"eventdate\":\"2016-10-05 00:00:00\",\"eventitle\":\"asdas\"},{\"eventdescription\":\"UpdateasddddLet\'s starts\",\"participantid\":\"{9,1,2,3,NULL,NULL,NULL,NULL,NULL,NULL}\",\"mainphotoid\":2,\"photosid\":\"{1,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL}\",\"ownerid\":3,\"invitationlist\":\"{2,4,7,8,NULL,NULL,NULL,NULL,NULL,NULL}\",\"privilligeId\":\"{1,2,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL}\",\"eventid\":4,\"eventdate\":\"2016-10-05 00:00:00\",\"eventitle\":\"asdasd\"},null,null,null,null,null,null,null]")

I am really desperate here i just hope that somebody can help me immediately

**Comment by BerkinSi** [comment]
I have used swiftyJson and could handle the nulls.

**Comment by diegoramosalmeida** [comment]
Hello dude, Please help me.

URL (GET) - "https://api.github.com/repos/ReactiveCocoa/ReactiveCocoa/pulls?state=all"

![image](https://user-images.githubusercontent.com/17261405/39675272-190c51d8-512f-11e8-9924-fd7084fd0d52.png)

![image](https://user-images.githubusercontent.com/17261405/39675440-85adb870-5131-11e8-8907-32980aed7c08.png)

![image](https://user-images.githubusercontent.com/17261405/39675344-2bfda4f8-5130-11e8-93c9-049e7468e32d.png)
...

Mapper below

![image](https://user-images.githubusercontent.com/17261405/39675356-72c9d6ea-5130-11e8-8d0e-23b61d810128.png)


I always got   
![image](https://user-images.githubusercontent.com/17261405/39675368-b017e91a-5130-11e8-89e5-e9ee8cc6b1f4.png)
