### ISSUE TITLE
Could I use My Own Error class?

### ISSUE THREAD

**Issue by anilustel** [tristanhimmelman/AlamofireObjectMapper#69]
Hi, normally Alamofire using for response
**response: Response (MyMappableObject, NSError) in**

And my service call return -> *code 500 with json*:
**{"errorMessage":"Mail and password not matched"}**

Could I use my own ErrorClass with object mapper? I mean change NSError with MyMappableErrorClass ?

my class just have one variable 
var errorMessage: String?

Thx.

**Comment by tristanhimmelman** [comment]
Unfortunately, at the moment this is not supported.
