### ISSUE TITLE
Framework not built when using Carthage

### ISSUE THREAD

**Issue by ryan-blunden** [tristanhimmelman/AlamofireObjectMapper#7]
I expected to see a AlamofireObjectMapper.framework file but can only see the frameworks for Alamofire and ObjectMapper.framework.

Below is the contents of my Cartfile

github "Alamofire/Alamofire" >= 1.2
github "tristanhimmelman/AlamofireObjectMapper" ~> 0.4

**Comment by apocolipse** [comment]
+1

**Comment by pizthewiz** [comment]
I think this has been fixed no?

**Comment by tristanhimmelman** [comment]
Yes this should no longer be an issue. Please target the latest version of: 
github "tristanhimmelman/AlamofireObjectMapper" ~> 0.6
