### ISSUE TITLE
Decreased performance on large JSON object in Swift 2.x

### ISSUE THREAD

**Issue by manojmahapatra** [tristanhimmelman/AlamofireObjectMapper#75]
I know this issues is a dupe of [https://github.com/Hearst-DD/ObjectMapper/issues/251](url), but still opening this to hope someone can give a direction how to fix it.

**Comment by tristanhimmelman** [comment]
I would prefer we maintain one discussion in the appropriate place. Closing this ticket. Please follow discussion here
https://github.com/Hearst-DD/ObjectMapper/issues/251
