### ISSUE TITLE
dependency issue with Alamofire 3.2

### ISSUE THREAD

**Issue by hamdan** [tristanhimmelman/AlamofireObjectMapper#77]
CocoaPods dependency issue with Alamofire 3.2

**Comment by AFcgi** [comment]
I publish a solution in this pull request: https://github.com/tristanhimmelman/AlamofireObjectMapper/pull/73

**Comment by mats-claassen** [comment]
+1

**Comment by tristanhimmelman** [comment]
I just merged #73 and pushed a new release to CocoaPods (v2.1.2)
