### ISSUE TITLE
[Carthage] Build error

### ISSUE THREAD

**Issue by hoangtuanfithou** [tristanhimmelman/AlamofireObjectMapper#78]
Dear tristanhimmelman,

1. Carthage build error
- Thank you for your great AlamofireObjectMapper, It is really helpful
- We used this, but for this weeks we see that log when run : 
carthage update --platform iOS
- Do you know the reason ? Thanks

github "tristanhimmelman/AlamofireObjectMapper" ~> 2.1

Failed to discover shared schemes in project Alamofire.xcodeproj—either the project does not have any shared schemes, or xcodebuild never returned

If you believe this to be a project configuration error, please file an issue with the maintainers at https://github.com/Alamofire/Alamofire/issues/new

2. Can your guide the way to make AlamofireObjectMapper support :
        Alamofire.upload(.POST, url, headers: self.getHeader(), multipartFormData: { multipartFormData in
...

Thanks so much

**Comment by hoangtuanfithou** [comment]
>>>Can your guide the way to make AlamofireObjectMapper support : Alamofire.upload(.POST, url, headers: self.getHeader(), multipartFormData: { multipartFormData in ...

I found it, sorry for dummy question :
            encodingCompletion: { encodingResult in
                switch encodingResult {
                case .Success(let upload, _, _):
                    upload.responseObject { (response: Response<T, NSError>) in
                        processResponse(response, callBack: callBack)
                    }
                
                case .Failure(let encodingError):
                    debugPrint(encodingError)
                    callBack(false, nil)
                }
            }

**Comment by hoangtuanfithou** [comment]
Dear tristanhimmelman,

Carthage build error
Thank you for your great AlamofireObjectMapper, It is really helpful
We used this, but for this weeks we see that log when run : carthage update --platform iOS
Do you know the reason ? Thanks
github "tristanhimmelman/AlamofireObjectMapper" ~> 2.1

Failed to discover shared schemes in project Alamofire.xcodeproj—either the project does not have any shared schemes, or xcodebuild never returned

If you believe this to be a project configuration error, please file an issue with the maintainers at https://github.com/Alamofire/Alamofire/issues/new

**Comment by cleexiang** [comment]
I have the same problem
