### ISSUE TITLE
Support for mapping onto existing objects 

### ISSUE THREAD

**Issue by ogezue** [tristanhimmelman/AlamofireObjectMapper#81]
I use ObjectMapper with Realm to have a persistant storage and to support an offline mode.

I realized that ObjectMapper recreates existing objects instead of updating them. I suppose it happens in this method of my object:

```
    required convenience init?(_ map: Map) {
        self.init()
    }
```

triggered from Mapper

```
	/// Maps a JSON dictionary to an object that conforms to Mappable
	public func map(JSONDictionary: [String : AnyObject]) -> N? {
		let map = Map(mappingType: .FromJSON, JSONDictionary: JSONDictionary)
		
		// check if N is of type MappableCluster
		if let klass = N.self as? MappableCluster.Type {
			if var object = klass.objectForMapping(map) as? N {
				object.mapping(map)
				return object
			}
		}
		
		if var object = N(map) {
			object.mapping(map)
			return object
		}
		return nil
	}
```

Is there something I have to do? My problem is that my objects has other properties that do not get loaded from the network and will be changed by the user manually.

**Comment by tristanhimmelman** [comment]
ObjectMapper actually has functions which you can use to map onto an existing object:
```
public func map(JSON: AnyObject?, toObject object: N) -> N
public func map(JSON: String, toObject object: N) -> N
public func map(JSONDictionary: [String : AnyObject], var toObject object: N) -> N
```
However, the AlamofireObjectMapper extension doesn't currently support these function. I think it would be a good addition though.

**Comment by ogezue** [comment]
It would be great if you would support this. Thank you!

**Comment by tristanhimmelman** [comment]
@ogezue I just added this functionality. See v3.0.0

**Comment by gunnarblom** [comment]
@tristanhimmelman @ogezue The added functionality doesn't support this scenario as the serialisation is done on another thread where the pre-fetched Realm can't be accessed. Isn't the best answer in the question here already, e.g. using MappableCluster for this?

**Comment by tristanhimmelman** [comment]
@gunnarblom you are right, this won't work for Realm objects. In that scenario, using the MappableCluster protocol is your best bet. Thanks for pointing that out, I hadn't considered the thread issue.

**Comment by ogezue** [comment]
Can you explain what a MappableCluster is an how to use it?

**Comment by tristanhimmelman** [comment]
@ogezue please see https://github.com/Hearst-DD/ObjectMapper#static-func-objectformappingmap-map---mappable

MappableCluster has now been merged into the `Mappable` protocol
