### ISSUE TITLE
Please update ObjectMapper dependency version

### ISSUE THREAD

**Issue by jonasman** [tristanhimmelman/AlamofireObjectMapper#83]
https://github.com/Hearst-DD/ObjectMapper#installation
current 1.1
In your podspec: 1.0

**Comment by AFcgi** [comment]
It isn't important. '~> 1.0' allow all versions of ObjectMapper up to 2.0. What's your problem with this dependency?

**Comment by tristanhimmelman** [comment]
@AFcgi is correct. Let me know if there is another issue.

**Comment by jonasman** [comment]
My bad then
