### ISSUE TITLE
Xcode 7.3: lot of warnings 

### ISSUE THREAD

**Issue by TofPlay** [tristanhimmelman/AlamofireObjectMapper#86]
Hi,
After installed Xcode 7.3 when I build with Carthage I have a lot of warnings:
```
warning: 'var' parameters are deprecated and will be removed in Swift 3
warning: '++' is deprecated: it will be removed in Swift 3
warning: keyword 'protocol' does not need to be escaped in argument list
```

**Comment by tristanhimmelman** [comment]
I have just released an update to ObjectMapper. I believe this resolve most of the warnings you are seeing. Please update your project.
