### ISSUE TITLE
Array of arrays?

### ISSUE THREAD

**Issue by robbiet480** [tristanhimmelman/AlamofireObjectMapper#88]
Hey,

How can I handle an array of arrays?

Here's an example of the JSON i'm trying to parse:

```json
[
  [
    {
      "entity_id": "light.ceiling_lights",
      "last_changed": "19:57:23 04-04-2016",
      "last_updated": "19:57:23 04-04-2016",
      "state": "on"
    }
  ]
]
```

I tried `.responseArray { (response: Response<Array<Array<HistoryResponse>>, NSError>) in` but get a "Cannot convert" error. 

Thanks for the help!

**Comment by tristanhimmelman** [comment]
Unfortunately we do not support this functionality at the time.

Side note: when using `.responseArray` you should not specify `Array` in the generic type parameter
