### ISSUE TITLE
Getting these errors in "TransformType.swift"

### ISSUE THREAD

**Issue by NMNiOS** [tristanhimmelman/AlamofireObjectMapper#89]
I have got the following errors

![screen shot 2016-04-08 at 12 17 36 pm](https://cloud.githubusercontent.com/assets/18345960/14379613/8625b72e-fd98-11e5-9906-63ad273a2ab4.png)
I am developing my first app, help me if possible

**Comment by ILI4S** [comment]
@NMNiOS which version of Xcode are you using? You may need to update it to support Swift 2.2.
