### ISSUE TITLE
Support Swift-2.0

### ISSUE THREAD

**Issue by kapoorsahil** [tristanhimmelman/AlamofireObjectMapper#9]
Error: Module file was created by an older version of the compiler.

**Comment by vigyanhoon** [comment]
Xcode 7b5 swift2.0 support needed

**Comment by kapoorsahil** [comment]
Any leads here dev? More than two months since the issue was created.

**Comment by tristanhimmelman** [comment]
A swift-2.0 branch is now available: https://github.com/tristanhimmelman/AlamofireObjectMapper/tree/swift-2.0
