### ISSUE TITLE
ObjectMapper for Xcode 7.2

### ISSUE THREAD

**Issue by karnakar** [tristanhimmelman/AlamofireObjectMapper#93]
Hi,

I'm unable to update to Xcode 7.3, what version can be used for Xcode 7.2

**Comment by tristanhimmelman** [comment]
Hi there, 

You will need to use any version of ObjectMapper prior to 1.2. 

AlamofireObjectMapper hasn't had any changes to support Xcode 7.3 so the current version of this library should be fine as long as ObjectMapper v1.2 is being used
