### ISSUE TITLE
Working with Dictionaries with unknown keys

### ISSUE THREAD

**Issue by patricks** [tristanhimmelman/AlamofireObjectMapper#96]
Hi, I have another special case, where I currently don't know how I should handle it.

The json looks like this:

```
{
	"config": {
		"url": "http://www.google.com",
		"countries": {
			"DE": "http://www.google.de",
			"IT": "http://www.google.it"
		}
	}
}
```

I understand how I can parse the url key. But how can I parse the different countries?

**Comment by patricks** [comment]
figured this out myself:

`var countries: Dictionary<String, String>?`

**Comment by tristanhimmelman** [comment]
I would map this as follows:
```
class Config: Mappable {
    var countries: Dictionary<String : NSURL>?
    required init?(_ map: Map){}

    func mapping(map: Map){
        countries <- (map["countries"], URLTransform())
    }
}
```

I believe the transform will work in this case. If not, your solution above works as well.
