### ISSUE TITLE
Error when building for device

### ISSUE THREAD

**Issue by smoi** [tristanhimmelman/AlamofireObjectMapper#99]
I'm using this method to get an object named "data"

.responseObject("data") { (response: Response) in

everything works fine if I build for the simulator but when I try to build for device i get this error 
Missing argument label 'queue:' in call 
It's like it is using a different kind of method that requires a queue.

**Comment by tristanhimmelman** [comment]
Alamofire now requires new parameter keywords. In your case, you need to insert `keyPath: `. It should look like:

`.responseObject(keyPath: "data") { (response: Response) in`

**Comment by smoi** [comment]
Why if I build for simulator I don't get this error and if I build for device I get it?
If I try to put the keypath i'm not able to build for simulator

**Comment by tristanhimmelman** [comment]
It shouldn't be any different. You might need to clean your project.

**Comment by smoi** [comment]
I found out that was an outdated version of the facebook sdk that is including alamofire
